import db from './db/schema.js';
import { v4 as uuidv4 } from 'uuid';
import oopLessons from './lessons/oop.js';
import stlLessons from './lessons/stl.js';
import sortingLessons from './lessons/sorting.js';
import linkedListLessons from './lessons/linkedlist.js';
import treeLessons from './lessons/trees.js';
import advancedLessons from './lessons/advanced.js';
import arrayProblems from './problems/arrays.js';
import stringProblems from './problems/strings.js';
import linkedListProblems from './problems/linkedlist.js';
import treeProblems from './problems/trees.js';
import stackQueueProblems from './problems/stacksqueues.js';
import dpProblems from './problems/dp.js';
import recursionProblems from './problems/recursion.js';
import graphProblems from './problems/graphs.js';
import binarySearchProblems from './problems/binarysearch.js';
import heapProblems from './problems/heaps.js';
import greedyProblems from './problems/greedy.js';
import sortingProblems from './problems/sorting.js';
import slidingWindowProblems from './problems/slidingwindow.js';
import twoPointerProblems from './problems/twopointers.js';
import bitManipulationProblems from './problems/bitmanipulation.js';
import mathsProblems from './problems/maths.js';
import matrixProblems from './problems/matrix.js';

const lessons = [
  {
    id: 'lesson-01', title: 'Hello World & Basic Syntax', category: 'basics', order_index: 1,
    content: `## What is C++?\n\nC++ is a powerful, high-performance programming language created by Bjarne Stroustrup in 1985. It extends the C language with object-oriented features and is used everywhere — from video games and operating systems to web browsers and financial systems.\n\n## Your First C++ Program\n\nEvery C++ program starts with the \`main()\` function. This is where execution begins and ends.\n\n\`\`\`cpp\n#include <iostream>\nusing namespace std;\n\nint main() {\n    cout << "Hello, World!" << endl;\n    return 0;\n}\n\`\`\`\n\n### Breaking It Down\n\n- \`#include <iostream>\` — Includes the input/output stream library\n- \`using namespace std;\` — Lets us use standard library names without \`std::\` prefix\n- \`int main()\` — The main function where program starts\n- \`cout << "...";\` — Prints text to the console\n- \`endl\` — Ends the line (like pressing Enter)\n- \`return 0;\` — Tells the OS the program ran successfully\n\n### Understanding the Structure\n\n**1. Preprocessor Directives (\`#include\`)**\nLines starting with \`#\` are processed before compilation. Common headers:\n- \`<iostream>\` — input/output\n- \`<cmath>\` — math functions\n- \`<string>\` — string operations\n- \`<vector>\` — dynamic arrays\n- \`<algorithm>\` — sorting, searching\n\n**2. The \`main()\` Function**\nEvery executable C++ program must have exactly ONE \`main\` function. It returns an integer to the operating system.\n\n**3. Statements and Semicolons**\nEvery statement in C++ ends with a semicolon (\`;\`). Think of it like a period at the end of a sentence.\n\n**4. Blocks and Braces**\nCurly braces \`{}\` group multiple statements into a single block.\n\n### Comments\n\`\`\`cpp\n// This is a single-line comment\n\n/*\n   This is a\n   multi-line comment\n*/\n\`\`\`\n\n### Common Mistakes for Beginners\n1. Missing semicolon — Every statement must end with \`;\`\n2. Case sensitivity — C++ is case-sensitive. \`main\` ≠ \`Main\`\n3. Mismatched braces — Every \`{\` must have a matching \`}\`\n4. Wrong quotes — Use \`"double quotes"\` for strings, \`'single'\` for characters\n\n### Practice Tips\n- Always indent your code consistently (2 or 4 spaces)\n- Use meaningful names for everything\n- Compile often — fix errors as they appear`,
    code_example: '#include <iostream>\nusing namespace std;\n\nint main() {\n    cout << "Welcome to C++!" << endl;\n    cout << "This is lesson 1" << endl;\n    cout << "Let\'s learn together!" << endl;\n    return 0;\n}'
  },
  {
    id: 'lesson-02', title: 'Variables & Data Types', category: 'basics', order_index: 2,
    content: `## What are Variables?\n\nVariables are named containers that store data in memory. Think of them as labeled boxes where you can put values, look at them later, and change them.\n\n## Variable Declaration and Initialization\n\n\`\`\`cpp\ntype variable_name = value;\n\`\`\`\n\n\`\`\`cpp\nint age = 25;           // Declaration + initialization\ndouble price;           // Declaration only (contains garbage value)\nprice = 99.99;          // Assignment\n\`\`\`\n\n## Basic Data Types\n\n| Type | Size | Range | Example |\n|------|------|-------|---------|\n| \`int\` | 4 bytes | -2.1B to 2.1B | \`int x = 42;\` |\n| \`float\` | 4 bytes | ~7 decimal digits | \`float f = 3.14f;\` |\n| \`double\` | 8 bytes | ~15 decimal digits | \`double d = 3.14;\` |\n| \`char\` | 1 byte | -128 to 127 | \`char c = \'A\';\` |\n| \`bool\` | 1 byte | true/false | \`bool flag = true;\` |\n\n## Type Modifiers\n\`\`\`cpp\nshort int s;           // Smaller int (2 bytes)\nlong int l;            // Larger int (4-8 bytes)\nlong long ll;          // Even larger (8 bytes)\nunsigned int u;        // Non-negative only (0 to 4.2B)\n\`\`\`\n\n## The \`auto\` Keyword (C++11)\nLet the compiler deduce the type automatically:\n\`\`\`cpp\nauto a = 42;           // int\nauto b = 3.14;         // double\nauto c = \'X\';          // char\nauto d = true;         // bool\n\`\`\`\n\n## Variable Naming Rules\n1. Can contain letters, digits, and underscores\n2. Must start with a letter or underscore\n3. Case-sensitive (\`age\` ≠ \`Age\`)\n4. Cannot use reserved keywords (\`int\`, \`return\`, \`if\`, etc.)\n5. Choose descriptive names!\n\n## Scope of Variables\nVariables exist only within the block where they\'re declared:\n\`\`\`cpp\nint global = 100;      // Accessible everywhere\n\nint main() {\n    int local = 50;    // Only in main()\n    if (true) {\n        int block = 10;// Only inside this if\n    }\n    return 0;\n}\n\`\`\`\n\n## Common Pitfalls\n1. Uninitialized variables — using a variable without assigning a value\n2. Overflow — storing a value too large for the type\n3. Type mismatch — assigning a float to an int loses precision\n4. Name shadowing — local variable hides a global one`,
    code_example: '#include <iostream>\nusing namespace std;\n\nint main() {\n    int age = 25;\n    float pi = 3.14159f;\n    double precise = 3.14159265358979;\n    char grade = \'A\';\n    bool isStudent = true;\n\n    cout << "Age: " << age << endl;\n    cout << "Pi: " << pi << endl;\n    cout << "Precision: " << precise << endl;\n    cout << "Grade: " << grade << endl;\n    cout << "Student: " << isStudent << endl;\n    cout << "Size of int: " << sizeof(int) << " bytes" << endl;\n\n    return 0;\n}'
  },
  {
    id: 'lesson-03', title: 'Constants & Literals', category: 'basics', order_index: 3,
    content: `## Constants\n\nConstants are variables whose values cannot be changed after initialization.\n\n### The \`const\` Keyword\n\`\`\`cpp\nconst int DAYS_IN_WEEK = 7;\nconst double PI = 3.14159;\n// DAYS_IN_WEEK = 8;  // ERROR — cannot modify a const\n\`\`\`\n\n### The \`constexpr\` Keyword (C++11)\nEvaluated at compile-time:\n\`\`\`cpp\nconstexpr int MAX_SIZE = 1000;\nconstexpr int AREA = MAX_SIZE * MAX_SIZE;\n\`\`\`\n\n### The \`#define\` Preprocessor Directive\n\`\`\`cpp\n#define PI 3.14159\n#define MAX_STUDENTS 30\n\`\`\`\n\nPrefer \`const\` over \`#define\` in modern C++.\n\n## Literals\n\nFixed values written directly in code.\n\n### Integer Literals\n\`\`\`cpp\nint decimal = 42;       // Decimal (base 10)\nint octal = 052;        // Octal (base 8)\nint hex = 0x2A;         // Hexadecimal (base 16)\nint binary = 0b101010;  // Binary (base 2) — C++14\n\`\`\`\n\n### Floating-Point Literals\n\`\`\`cpp\ndouble d1 = 3.14159;\ndouble d2 = 3.14159e5;  // Scientific notation\nfloat f = 3.14f;         // f suffix for float\n\`\`\`\n\n### Character and String Literals\n\`\`\`cpp\nchar letter = \'A\';\nchar newline = \'\\\\n\';\nstring name = "Alice";\n\`\`\`\n\n### Escape Sequences\n| Sequence | Meaning |\n|----------|---------|\n| \`\\\\n\` | Newline |\n| \`\\\\t\` | Tab |\n| \`\\\\\\\\\` | Backslash |\n| \`\\\\"\` | Double quote |\n| \`\\\\\'\` | Single quote |\n\n### Boolean Literals\n\`\`\`cpp\nbool isReady = true;\nbool isDone = false;\n\`\`\`\n\n## When to Use What\n| Situation | Recommendation |\n|-----------|---------------|\n| Simple numeric constant | \`const\` or \`constexpr\` |\n| Array size | \`constexpr\` |\n| String constant | \`const string\` |\n| Legacy C code | \`#define\` |`,
    code_example: '#include <iostream>\nusing namespace std;\n\nconstexpr int SECONDS_PER_HOUR = 3600;\nconstexpr int HOURS_PER_DAY = 24;\n\nint main() {\n    int days = 5;\n    int totalSeconds = days * SECONDS_PER_HOUR * HOURS_PER_DAY;\n    cout << "Seconds in " << days << " days: " << totalSeconds << endl;\n\n    int hexVal = 0xFF;\n    int binaryVal = 0b1111;\n    double scientific = 1.5e3;\n\n    cout << "0xFF = " << hexVal << endl;\n    cout << "0b1111 = " << binaryVal << endl;\n    cout << "1.5e3 = " << scientific << endl;\n\n    return 0;\n}'
  },
  {
    id: 'lesson-04', title: 'Basic I/O (Input/Output)', category: 'basics', order_index: 4,
    content: `## Console I/O in C++\n\nInput/output (I/O) lets your program communicate with the outside world.\n\n## Output with \`cout\`\n\`\`\`cpp\ncout << "Hello!";\ncout << 42;\ncout << "Value: " << x;\n\`\`\`\n\n### Formatting with \`<iomanip>\`\n\`\`\`cpp\n#include <iomanip>\n\ncout << setw(10) << "Name";\ncout << fixed << setprecision(2) << 3.14159;\ncout << setfill(\'*\') << setw(10) << 42;\n\`\`\`\n\n## Input with \`cin\`\n\`\`\`cpp\nint age;\ncout << "Enter your age: ";\ncin >> age;\n\nstring name;\ngetline(cin, name);  // Reads entire line including spaces\n\`\`\`\n\n**Important**: \`cin >>\` leaves newline in buffer — use \`cin.ignore()\` before \`getline\`!\n\n## Common I/O Manipulators\n| Manipulator | Effect |\n|-------------|--------|\n| \`endl\` | Insert newline and flush buffer |\n| \`setw(n)\` | Set field width to n |\n| \`setprecision(n)\` | Set decimal precision |\n| \`fixed\` | Fixed-point notation |\n| \`left / right\` | Text alignment |\n| \`setfill(c)\` | Fill character |\n| \`boolalpha\` | Print bool as true/false |\n\n## Error Output\n\`\`\`cpp\ncerr << "Error: division by zero!" << endl;   // Unbuffered error\nclog << "Log: operation started" << endl;     // Buffered log\n\`\`\`\n\n## Input Validation\n\`\`\`cpp\nint number;\nif (cin >> number) {\n    cout << "You entered: " << number << endl;\n} else {\n    cout << "Invalid input!" << endl;\n    cin.clear();\n    cin.ignore(10000, \'\\\\n\');\n}\n\`\`\``,
    code_example: '#include <iostream>\n#include <iomanip>\n#include <string>\nusing namespace std;\n\nint main() {\n    string name;\n    int age;\n    double height;\n\n    cout << "Enter your name: ";\n    getline(cin, name);\n\n    cout << "Enter your age: ";\n    cin >> age;\n\n    cout << "Enter your height (meters): ";\n    cin >> height;\n\n    cout << left << setw(15) << "Name:" << name << endl;\n    cout << setw(15) << "Age:" << age << " years" << endl;\n    cout << fixed << setprecision(2);\n    cout << setw(15) << "Height:" << height << " m" << endl;\n\n    return 0;\n}'
  },
  {
    id: 'lesson-05', title: 'Operators in C++', category: 'basics', order_index: 5,
    content: `## What are Operators?\n\nOperators are symbols that perform operations on values (operands). C++ has a rich set of operators.\n\n## 1. Arithmetic Operators\n\`\`\`cpp\nint a = 10, b = 3;\nint sum = a + b;     // 13 — addition\nint diff = a - b;    // 7 — subtraction\nint prod = a * b;    // 30 — multiplication\nint quot = a / b;    // 3 — integer division (truncates!)\nint rem = a % b;     // 1 — modulo (remainder)\n\`\`\`\n\n**Important**: Integer division truncates! \`10 / 3 = 3\`, not 3.333.\n\n## 2. Relational Operators\n\`\`\`cpp\nx == y  // equal to\nx != y  // not equal to\nx < y   // less than\nx > y   // greater than\nx <= y  // less than or equal\nx >= y  // greater than or equal\n\`\`\`\n\n## 3. Logical Operators\n\`\`\`cpp\na && b   // AND (both must be true)\na || b   // OR (at least one true)\n!a       // NOT (inverts)\n\`\`\`\n\n**Short-circuit evaluation**: \`&&\` and \`||\` stop evaluating once the result is known.\n\n## 4. Bitwise Operators\n\`\`\`cpp\nunsigned char a = 0b1100;  // 12\nunsigned char b = 0b1010;  // 10\n\na & b   // 0b1000 (8)  — AND\na | b   // 0b1110 (14) — OR\na ^ b   // 0b0110 (6)  — XOR\n~a      // 0b0011 (3)  — NOT\na << 1  // 0b1000 (24) — left shift\na >> 1  // 0b0110 (6)  — right shift\n\`\`\`\n\n## 5. Assignment Operators\n\`\`\`cpp\nx += 5;   // x = x + 5\nx -= 3;   // x = x - 3\nx *= 2;   // x = x * 2\nx /= 4;   // x = x / 4\nx %= 3;   // x = x % 3\n\`\`\`\n\n## 6. Increment/Decrement\n\`\`\`cpp\nint a = 5;\nint b = a++;    // b = 5, a = 6 (post-increment)\nint c = ++a;    // c = 7, a = 7 (pre-increment)\n\`\`\`\n\n## 7. Ternary Operator\n\`\`\`cpp\nint max = (a > b) ? a : b;\nstring status = (age >= 18) ? "Adult" : "Minor";\n\`\`\`\n\n## Operator Precedence (simplified)\n1. \`()\` \`[]\` \`->\` \`.\`\n2. \`!\` \`~\` \`++\` \`--\` (unary)\n3. \`*\` \`/\` \`%\`\n4. \`+\` \`-\`\n5. \`<<\` \`>>\`\n6. \`<\` \`<=\` \`>\` \`>=\`\n7. \`==\` \`!=\`\n8. \`&&\`\n9. \`||\`\n10. \`?:\` (ternary)\n11. \`=\` \`+=\` etc.\n\n**Rule of thumb**: When in doubt, use parentheses!`,
    code_example: '#include <iostream>\nusing namespace std;\n\nint main() {\n    int a = 15, b = 4;\n\n    cout << "a = " << a << ", b = " << b << endl;\n    cout << "a + b = " << (a + b) << endl;\n    cout << "a - b = " << (a - b) << endl;\n    cout << "a * b = " << (a * b) << endl;\n    cout << "a / b = " << (a / b) << " (integer division)" << endl;\n    cout << "a % b = " << (a % b) << endl;\n\n    int age = 20;\n    cout << age << " -> " << (age >= 18 ? "Adult" : "Minor") << endl;\n\n    cout << "12 & 10 = " << (12 & 10) << endl;\n    cout << "12 << 1 = " << (12 << 1) << " (multiply by 2)" << endl;\n\n    return 0;\n}'
  },
  {
    id: 'lesson-06', title: 'Type Conversion & Casting', category: 'basics', order_index: 6,
    content: `## Type Conversion\n\nWhen different types are used in an expression, C++ automatically converts them to a common type.\n\n### Implicit Conversion\n\`\`\`cpp\nint i = 42;\ndouble d = i;       // int → double (safe)\n\ndouble pi = 3.14;\nint x = pi;         // double → int (lossy! x = 3)\n\`\`\`\n\n### The Conversion Hierarchy\n\`bool → char → short → int → unsigned → long → long long → float → double → long double\`\n\nConverting "down" the hierarchy can lose information.\n\n## Explicit Casting\n\n### C-style Cast (Avoid)\n\`\`\`cpp\nint x = (int)3.14;\n\`\`\`\n\n### C++ Casts (Prefer These)\n\n#### 1. \`static_cast\` (Most Common)\n\`\`\`cpp\ndouble pi = 3.14159;\nint approx = static_cast<int>(pi);\nchar c = static_cast<char>(65);  // \'A\'\n\`\`\`\n\n#### 2. \`dynamic_cast\`\n\`\`\`cpp\nif (Derived* d = dynamic_cast<Derived*>(base)) {\n    d->derivedMethod();\n}\n\`\`\`\n\n#### 3. \`const_cast\`\n\`\`\`cpp\nconst int x = 42;\nint* p = const_cast<int*>(&x);\n\`\`\`\n\n#### 4. \`reinterpret_cast\`\n\`\`\`cpp\nfloat* p = reinterpret_cast<float*>(&x);\n\`\`\`\n\n## Numeric Conversion Pitfalls\n\`\`\`cpp\nunsigned int u = 0;\nu--;  // Wraps to 4294967295! (unsigned underflow)\n\nfloat f = 0.1f;\ndouble d = 0.1;\ncout << (f == d);  // false! Different precision\n\`\`\`\n\n## Best Practices\n1. Prefer \`static_cast\` over C-style casts\n2. Use \`dynamic_cast\` for polymorphic downcasting\n3. Avoid \`const_cast\` unless necessary\n4. Be aware of implicit conversions — they can hide bugs`,
    code_example: '#include <iostream>\nusing namespace std;\n\nint main() {\n    int a = 42;\n    double b = a;\n    cout << "int " << a << " -> double " << b << endl;\n\n    double pi = 3.14159;\n    int truncated = static_cast<int>(pi);\n    cout << "static_cast<int>(" << pi << ") = " << truncated << endl;\n\n    char letter = \'Z\';\n    int ascii = static_cast<int>(letter);\n    cout << "ASCII of " << letter << " is " << ascii << endl;\n\n    int num = 10, den = 3;\n    double result = static_cast<double>(num) / den;\n    cout << num << "/" << den << " = " << result << " (with cast)" << endl;\n\n    return 0;\n}'
  },
  {
    id: 'lesson-07', title: 'If/Else & Switch Statements', category: 'control-flow', order_index: 7,
    content: `## Making Decisions in Code\n\nControl flow statements let your code make decisions and execute different paths based on conditions.\n\n## The \`if\` Statement\n\`\`\`cpp\nif (condition) {\n    // Runs if condition is true\n}\n\`\`\`\n\n## \`if-else\`\n\`\`\`cpp\nif (condition) {\n    // Runs if condition is true\n} else {\n    // Runs if condition is false\n}\n\`\`\`\n\n## \`if-else if-else\`\n\`\`\`cpp\nif (grade >= 90)      cout << "A";\nelse if (grade >= 80) cout << "B";\nelse if (grade >= 70) cout << "C";\nelse if (grade >= 60) cout << "D";\nelse                  cout << "F";\n\`\`\`\n\n## The \`switch\` Statement\nUse when comparing a single value against many constants:\n\`\`\`cpp\nchar grade = \'B\';\nswitch (grade) {\n    case \'A\': cout << "Excellent!"; break;\n    case \'B\': cout << "Good job!";  break;\n    case \'C\': cout << "Fair";       break;\n    case \'D\': cout << "Needs work"; break;\n    case \'F\': cout << "Failed";     break;\n    default:  cout << "Invalid";\n}\n\`\`\`\n\n### Important Switch Rules\n1. Expression must be integral (int, char, enum)\n2. \`break\` is needed to exit — without it, execution "falls through"\n3. \`default\` handles unmatched values\n\n## Common Mistakes\n1. Using \`=\` instead of \`==\`: \`if (x = 5)\` assigns 5 and is always true!\n2. Missing braces: \`if (x > 0) doA(); doB();\` — only doA() is conditional\n3. Missing \`break\` in switch — causes fall-through\n\n## Best Practices\n- Always use braces \`{}\` even for single-line bodies\n- Keep conditions simple — extract complex logic into boolean variables\n- Use \`default\` in switch to handle unexpected values`,
    code_example: '#include <iostream>\nusing namespace std;\n\nint main() {\n    int score;\n    cout << "Enter your score (0-100): ";\n    cin >> score;\n\n    if (score < 0 || score > 100) {\n        cout << "Invalid score!" << endl;\n        return 1;\n    }\n\n    char grade;\n    if (score >= 90) grade = \'A\';\n    else if (score >= 80) grade = \'B\';\n    else if (score >= 70) grade = \'C\';\n    else if (score >= 60) grade = \'D\';\n    else grade = \'F\';\n\n    cout << "Grade: " << grade << endl;\n\n    switch (grade) {\n        case \'A\': cout << "Excellent!"; break;\n        case \'B\': cout << "Good!"; break;\n        case \'C\': cout << "Fair"; break;\n        case \'D\': cout << "Needs work"; break;\n        case \'F\': cout << "Failed"; break;\n    }\n    cout << endl;\n\n    string status = (score >= 60) ? "PASSED" : "FAILED";\n    cout << "Status: " << status << endl;\n\n    return 0;\n}'
  },
  {
    id: 'lesson-08', title: 'Loops in C++', category: 'control-flow', order_index: 8,
    content: `## Why Loops?\n\nLoops let you repeat a block of code multiple times.\n\n## 1. The \`for\` Loop\nUse when you know how many times to repeat:\n\`\`\`cpp\nfor (initialization; condition; update) {\n    // body\n}\n\nfor (int i = 1; i <= 5; i++) {\n    cout << i << " ";  // 1 2 3 4 5\n}\n\`\`\`\n\n### Parts of a For Loop\n| Part | Purpose |\n|------|---------|\n| Initialization | Runs once before loop |\n| Condition | Checked before each iteration |\n| Update | Runs after each iteration |\n\n## 2. The \`while\` Loop\nUse when you don\'t know how many times to repeat:\n\`\`\`cpp\nwhile (condition) {\n    // body\n}\n\nint n = 12345, sum = 0;\nwhile (n > 0) {\n    sum += n % 10;\n    n /= 10;\n}\ncout << sum;  // 15\n\`\`\`\n\n## 3. The \`do-while\` Loop\nBody runs AT LEAST ONCE:\n\`\`\`cpp\ndo {\n    // body\n} while (condition);\n\nint number;\ndo {\n    cout << "Enter a positive number: ";\n    cin >> number;\n} while (number <= 0);\n\`\`\`\n\n## 4. Range-Based For Loop (C++11)\n\`\`\`cpp\nint arr[] = {10, 20, 30, 40, 50};\nfor (int x : arr) {\n    cout << x << " ";\n}\n\`\`\`\n\n## Loop Control: \`break\` and \`continue\`\n- \`break\` — Exit the loop immediately\n- \`continue\` — Skip to the next iteration\n\n\`\`\`cpp\nfor (int i = 0; i < 10; i++) {\n    if (i % 2 == 0) continue;  // Skip evens\n    if (i > 7) break;           // Stop after 7\n    cout << i << " ";           // 1 3 5 7\n}\n\`\`\`\n\n## Nested Loops\n\`\`\`cpp\nfor (int i = 0; i < 3; i++) {\n    for (int j = 0; j < 3; j++) {\n        cout << "(" << i << "," << j << ") ";\n    }\n}\n\`\`\`\n\n## Infinite Loops\n\`\`\`cpp\n// Usually a bug:\nfor (int i = 10; i > 0; i++) { }  // i goes up forever!\n\n// Sometimes intentional:\nwhile (true) {\n    if (shouldStop) break;\n}\n\`\`\``,
    code_example: '#include <iostream>\nusing namespace std;\n\nint main() {\n    cout << "For loop 1-5: ";\n    for (int i = 1; i <= 5; i++) cout << i << " ";\n    cout << endl;\n\n    int n = 5, fact = 1;\n    while (n > 1) { fact *= n; n--; }\n    cout << "Factorial: " << fact << endl;\n\n    cout << "Pattern:\\n";\n    for (int i = 1; i <= 5; i++) {\n        for (int j = 1; j <= i; j++) cout << "* ";\n        cout << endl;\n    }\n\n    int arr[] = {2, 4, 6, 8, 10};\n    cout << "Range-based: ";\n    for (int x : arr) cout << x << " ";\n    cout << endl;\n\n    return 0;\n}'
  },
  {
    id: 'lesson-09', title: 'Control Flow Best Practices', category: 'control-flow', order_index: 9,
    content: `## Writing Clean Control Flow\n\nProfessional code is readable, maintainable, and predictable.\n\n## 1. Early Return (Guard Clauses)\nInstead of deeply nested ifs, return early:\n\`\`\`cpp\n// BAD — Deep nesting\nstring processOrder(Order* order) {\n    if (order != nullptr) {\n        if (order->isValid()) {\n            if (order->isPaid()) {\n                return "Processed";\n            } else { return "Not paid"; }\n        } else { return "Invalid"; }\n    }\n    return "No order";\n}\n\n// GOOD — Guard clauses\nstring processOrder(Order* order) {\n    if (order == nullptr) return "No order";\n    if (!order->isValid()) return "Invalid";\n    if (!order->isPaid()) return "Not paid";\n    return "Processed";\n}\n\`\`\`\n\n## 2. Avoid Magic Numbers\n\`\`\`cpp\n// BAD\nif (temperature > 100) { ... }\n\n// GOOD\nconstexpr int BOILING_POINT = 100;\nif (temperature > BOILING_POINT) { ... }\n\`\`\`\n\n## 3. Simplify Complex Conditions\n\`\`\`cpp\n// BAD\nif (age >= 18 && age <= 65 && hasID && !isBlacklisted) { ... }\n\n// GOOD\nbool canEnter = age >= 18 && age <= 65 && hasID;\nbool isAllowed = canEnter && !isBlacklisted;\nif (isAllowed) { ... }\n\`\`\`\n\n## 4. De Morgan\'s Laws\n\`\`\`cpp\n// !(A && B) = !A || !B\n// !(A || B) = !A && !B\n\n// BAD\nif (!(isReady && isValid)) { ... }\n\n// GOOD\nif (!isReady || !isValid) { ... }\n\`\`\`\n\n## 5. Switch Best Practices\n- Always include \`default\`\n- Keep cases short\n- Document intentional fall-through\n\n## 6. Avoid \`goto\`\nUse RAII and structured alternatives instead.\n\n## Summary\n- Guard clauses > nested ifs\n- Named constants > magic numbers\n- Simple conditions > complex ones\n- Let the structure of your code reflect the logic`,
    code_example: '#include <iostream>\nusing namespace std;\n\nstring getAgeCategory(int age) {\n    if (age < 0) return "Invalid";\n    if (age < 13) return "Child";\n    if (age < 20) return "Teen";\n    if (age < 65) return "Adult";\n    return "Senior";\n}\n\nint main() {\n    int ages[] = {-5, 10, 17, 25, 70};\n    for (int age : ages) {\n        cout << "Age " << age << ": " << getAgeCategory(age) << endl;\n    }\n\n    bool isWeekend = true;\n    bool isHoliday = false;\n\n    if (isWeekend || isHoliday) {\n        cout << "No work today!" << endl;\n    }\n\n    // Equivalent using De Morgan\n    if (!(!isWeekend && !isHoliday)) {\n        cout << "Indeed, no work!" << endl;\n    }\n\n    return 0;\n}'
  },
  {
    id: 'lesson-10', title: 'Error Handling Basics', category: 'control-flow', order_index: 10,
    content: `## Why Error Handling?\n\nPrograms encounter errors: invalid input, missing files, division by zero. Proper error handling makes your programs robust.\n\n## 1. Checking Return Values\n\`\`\`cpp\nint divide(int a, int b, int& result) {\n    if (b == 0) return -1;  // Error\n    result = a / b;\n    return 0;               // Success\n}\n\`\`\`\n\n## 2. The \`assert\` Macro\nFor debugging — aborts if condition is false:\n\`\`\`cpp\n#include <cassert>\nassert(b != 0 && "Division by zero!");\n\`\`\`\n\nAssertions are removed in release builds (when \`NDEBUG\` is defined).\n\n## 3. Exceptions\n\n### Throwing\n\`\`\`cpp\ndouble divide(double a, double b) {\n    if (b == 0.0) {\n        throw runtime_error("Division by zero!");\n    }\n    return a / b;\n}\n\`\`\`\n\n### Catching\n\`\`\`cpp\ntry {\n    double result = divide(10.0, 0.0);\n}\ncatch (const runtime_error& e) {\n    cout << "Error: " << e.what() << endl;\n}\ncatch (...) {\n    cout << "Unknown error" << endl;\n}\n\`\`\`\n\n### Standard Exception Types\n| Exception | Use |\n|-----------|-----|\n| \`runtime_error\` | Runtime errors |\n| \`logic_error\` | Logic/precondition violations |\n| \`invalid_argument\` | Invalid function argument |\n| \`out_of_range\` | Index out of bounds |\n| \`bad_alloc\` | Memory allocation failure |\n\n### When to Use Exceptions\n**Use for:**\n- Errors that can\'t be handled locally\n- Constructor failures\n- Operator overloads\n\n**Don\'t use for:**\n- Normal control flow (expensive!)\n- Expected, frequent errors (validate instead)\n\n## 4. RAII and Error Handling\n\`\`\`cpp\nvoid processFile(const string& filename) {\n    ifstream file(filename);\n    if (!file) throw runtime_error("Cannot open file");\n    // File automatically closes when \'file\' goes out of scope\n    // Even if an exception is thrown!\n}\n\`\`\`\n\n## Best Practices\n1. Use exceptions for exceptional situations\n2. Catch by const reference\n3. Order catch blocks from most specific to most general\n4. Never throw from a destructor\n5. Use RAII to prevent resource leaks`,
    code_example: '#include <iostream>\n#include <stdexcept>\n#include <cmath>\nusing namespace std;\n\ndouble safeSqrt(double x) {\n    if (x < 0) throw invalid_argument("Cannot sqrt negative");\n    return sqrt(x);\n}\n\nint main() {\n    double inputs[] = {16, -4, 9, 25};\n    for (double a : inputs) {\n        cout << "sqrt(" << a << ") = ";\n        try {\n            double r = safeSqrt(a);\n            cout << r << endl;\n        } catch (const exception& e) {\n            cout << "Error: " << e.what() << endl;\n        }\n    }\n    return 0;\n}'
  },
  {
    id: 'lesson-11', title: 'Functions', category: 'functions', order_index: 11,
    content: `## What are Functions?\n\nFunctions are reusable blocks of code that perform a specific task.\n\n## Function Syntax\n\`\`\`cpp\nreturn_type function_name(parameter_list) {\n    // body\n    return value;\n}\n\`\`\`\n\n## A Simple Function\n\`\`\`cpp\nint add(int a, int b) {\n    return a + b;\n}\n\nint main() {\n    int sum = add(5, 3);  // sum = 8\n}\n\`\`\`\n\n## Declaration vs Definition\n\`\`\`cpp\n// Declaration (prototype)\nint multiply(int x, int y);\n\nint main() {\n    cout << multiply(4, 5);  // Uses declaration\n}\n\n// Definition\nint multiply(int x, int y) {\n    return x * y;\n}\n\`\`\`\n\n## Parameters\n\n### Pass by Value (Default)\nA copy is made — changes don\'t affect the original:\n\`\`\`cpp\nvoid increment(int x) { x++; }\nint a = 5;\nincrement(a);\ncout << a;  // Still 5!\n\`\`\`\n\n### Pass by Reference\nChanges affect the original:\n\`\`\`cpp\nvoid increment(int& x) { x++; }\nint a = 5;\nincrement(a);\ncout << a;  // 6!\n\`\`\`\n\n### Pass by Const Reference\nFor efficiency (no copy) without modification:\n\`\`\`cpp\nvoid printInfo(const string& name) {\n    cout << name;\n}\n\`\`\`\n\n## Return Types\n\`\`\`cpp\nvoid greet(const string& name) {          // No return\n    cout << "Hello, " << name << "!";\n}\n\nint square(int x) { return x * x; }        // Returns value\n\`\`\`\n\n## Inline Functions\n\`\`\`cpp\ninline int square(int x) { return x * x; }\n\`\`\`\n\n## Best Practices\n1. Each function should do ONE thing well\n2. Keep functions short (< 30 lines)\n3. Use descriptive names\n4. Pass large objects by const reference`,
    code_example: '#include <iostream>\nusing namespace std;\n\nint add(int a, int b) { return a + b; }\nint subtract(int a, int b) { return a - b; }\nint multiply(int a, int b) { return a * b; }\ndouble divide(double a, double b) { return a / b; }\n\nint main() {\n    int x = 20, y = 7;\n    cout << x << " + " << y << " = " << add(x, y) << endl;\n    cout << x << " - " << y << " = " << subtract(x, y) << endl;\n    cout << x << " * " << y << " = " << multiply(x, y) << endl;\n    cout << x << " / " << y << " = " << divide(x, y) << endl;\n    return 0;\n}'
  }
];

const problems = [
  {
    id: 'prob-01', title: 'Two Sum', difficulty: 'easy', category: 'arrays',
    description: `Given an array of integers \`nums\` and an integer \`target\`, return indices of the two numbers such that they add up to \`target\`.\n\nYou may assume that each input would have exactly one solution, and you may not use the same element twice.\n\nYou can return the answer in any order.`,
    examples: [
      { input: 'nums = [2,7,11,15], target = 9', output: '[0,1]', explanation: 'Because nums[0] + nums[1] == 9, we return [0, 1].' },
      { input: 'nums = [3,2,4], target = 6', output: '[1,2]', explanation: 'Because nums[1] + nums[2] == 6, we return [1, 2].' }
    ],
    constraints: '2 <= nums.length <= 10^4, -10^9 <= nums[i] <= 10^9, -10^9 <= target <= 10^9',
    solution_template: '#include <iostream>\n#include <vector>\nusing namespace std;\n\nvector<int> twoSum(vector<int>& nums, int target) {\n    // Write your solution here\n    return {};\n}\n\nint main() {\n    vector<int> nums = {2, 7, 11, 15};\n    int target = 9;\n    vector<int> result = twoSum(nums, target);\n    cout << "[" << result[0] << "," << result[1] << "]" << endl;\n    return 0;\n}',
    test_cases: [
      { input: '', expected: '[0,1]' }
    ]
  },
  {
    id: 'prob-02', title: 'Reverse a String', difficulty: 'easy', category: 'strings',
    description: `Write a function that reverses a string. The input string is given as an array of characters \`s\`.\n\nYou must do this by modifying the input array in-place with O(1) extra memory.`,
    examples: [
      { input: 's = ["h","e","l","l","o"]', output: '["o","l","l","e","h"]' },
      { input: 's = ["H","a","n","n","a","h"]', output: '["h","a","n","n","a","H"]' }
    ],
    constraints: '1 <= s.length <= 10^5, s[i] is a printable ascii character',
    solution_template: '#include <iostream>\n#include <vector>\nusing namespace std;\n\nvoid reverseString(vector<char>& s) {\n    // Write your solution here\n}\n\nint main() {\n    vector<char> s = {\'h\',\'e\',\'l\',\'l\',\'o\'};\n    reverseString(s);\n    for (char c : s) cout << c;\n    cout << endl;\n    return 0;\n}',
    test_cases: [
      { input: '', expected: 'olleh' }
    ]
  },
  {
    id: 'prob-03', title: 'Fibonacci Number', difficulty: 'easy', category: 'recursion',
    description: `The Fibonacci numbers, commonly denoted \`F(n)\`, form a sequence called the Fibonacci sequence such that each number is the sum of the two preceding ones, starting from 0 and 1.\n\n\`F(0) = 0, F(1) = 1\`\n\`F(n) = F(n - 1) + F(n - 2), for n > 1\`\n\nGiven \`n\`, calculate \`F(n)\`.`,
    examples: [
      { input: 'n = 2', output: '1', explanation: 'F(2) = F(1) + F(0) = 1 + 0 = 1.' },
      { input: 'n = 3', output: '2', explanation: 'F(3) = F(2) + F(1) = 1 + 1 = 2.' },
      { input: 'n = 4', output: '3', explanation: 'F(4) = F(3) + F(2) = 2 + 1 = 3.' }
    ],
    constraints: '0 <= n <= 30',
    solution_template: '#include <iostream>\nusing namespace std;\n\nint fib(int n) {\n    // Write your solution here\n    return 0;\n}\n\nint main() {\n    int n = 10;\n    cout << fib(n) << endl;\n    return 0;\n}',
    test_cases: [
      { input: '', expected: '55' }
    ]
  },
  {
    id: 'prob-04', title: 'Valid Parentheses', difficulty: 'easy', category: 'stacks',
    description: `Given a string \`s\` containing just the characters \'(\', \')\', \'{\', \'}\', \'[\' and \']\', determine if the input string is valid.\n\nAn input string is valid if:\n1. Open brackets must be closed by the same type of brackets.\n2. Open brackets must be closed in the correct order.\n3. Every close bracket has a corresponding open bracket of the same type.`,
    examples: [
      { input: 's = "()"', output: 'true' },
      { input: 's = "()[]{}"', output: 'true' },
      { input: 's = "(]"', output: 'false' }
    ],
    constraints: '1 <= s.length <= 10^4, s consists of parentheses only',
    solution_template: '#include <iostream>\n#include <stack>\nusing namespace std;\n\nbool isValid(string s) {\n    // Write your solution here\n    return false;\n}\n\nint main() {\n    string s = "()[]{}";\n    cout << (isValid(s) ? "true" : "false") << endl;\n    return 0;\n}',
    test_cases: [
      { input: '', expected: 'true' }
    ]
  },
  {
    id: 'prob-05', title: 'Linked List Cycle Detection', difficulty: 'easy', category: 'linked-list',
    description: `Given \`head\`, the head of a linked list, determine if the linked list has a cycle in it.\n\nThere is a cycle in a linked list if there is some node in the list that can be reached again by continuously following the \`next\` pointer.\n\nReturn \`true\` if there is a cycle in the linked list. Otherwise, return \`false\`.`,
    examples: [
      { input: 'head = [3,2,0,-4], pos = 1', output: 'true', explanation: 'The tail connects to the node at index 1.' },
      { input: 'head = [1,2], pos = 0', output: 'false', explanation: 'The tail connects to the node at index 0.' }
    ],
    constraints: 'The number of nodes in the list is in range [0, 10^4].',
    solution_template: '#include <iostream>\nusing namespace std;\n\nstruct ListNode {\n    int val;\n    ListNode *next;\n    ListNode(int x) : val(x), next(nullptr) {}\n};\n\nbool hasCycle(ListNode *head) {\n    // Write your solution here (Floyd\'s algorithm)\n    return false;\n}\n\nint main() {\n    ListNode* head = new ListNode(3);\n    head->next = new ListNode(2);\n    head->next->next = new ListNode(0);\n    head->next->next->next = new ListNode(-4);\n    head->next->next->next->next = head->next;  // create cycle\n    cout << (hasCycle(head) ? "true" : "false") << endl;\n    return 0;\n}',
    test_cases: [
      { input: '', expected: 'true' }
    ]
  },
  {
    id: 'prob-06', title: 'Binary Search', difficulty: 'easy', category: 'searching',
    description: `Given an array of integers \`nums\` which is sorted in ascending order, and an integer \`target\`, write a function to search \`target\` in \`nums\`. If \`target\` exists, then return its index. Otherwise, return \`-1\`.\n\nYou must write an algorithm with O(log n) runtime complexity.`,
    examples: [
      { input: 'nums = [-1,0,3,5,9,12], target = 9', output: '4', explanation: '9 exists in nums and its index is 4' },
      { input: 'nums = [-1,0,3,5,9,12], target = 2', output: '-1', explanation: '2 does not exist in nums, return -1' }
    ],
    constraints: '1 <= nums.length <= 10^4, -10^4 < nums[i] < 10^4',
    solution_template: '#include <iostream>\n#include <vector>\nusing namespace std;\n\nint search(vector<int>& nums, int target) {\n    // Write your binary search solution\n    return -1;\n}\n\nint main() {\n    vector<int> nums = {-1, 0, 3, 5, 9, 12};\n    int target = 9;\n    cout << search(nums, target) << endl;\n    return 0;\n}',
    test_cases: [
      { input: '', expected: '4' }
    ]
  },
  {
    id: 'prob-07', title: 'Bubble Sort', difficulty: 'easy', category: 'sorting',
    description: `Implement the Bubble Sort algorithm to sort an array of integers in ascending order.\n\nBubble sort works by repeatedly swapping adjacent elements if they are in the wrong order.`,
    examples: [
      { input: 'nums = [64, 34, 25, 12, 22, 11, 90]', output: '[11, 12, 22, 25, 34, 64, 90]' }
    ],
    constraints: '1 <= nums.length <= 100',
    solution_template: '#include <iostream>\nusing namespace std;\n\nvoid bubbleSort(int arr[], int n) {\n    // Write bubble sort here\n}\n\nint main() {\n    int arr[] = {64, 34, 25, 12, 22, 11, 90};\n    int n = sizeof(arr)/sizeof(arr[0]);\n    bubbleSort(arr, n);\n    for (int i = 0; i < n; i++) cout << arr[i] << " ";\n    cout << endl;\n    return 0;\n}',
    test_cases: [
      { input: '', expected: '11 12 22 25 34 64 90' }
    ]
  },
  {
    id: 'prob-08', title: 'Inorder Tree Traversal', difficulty: 'easy', category: 'trees',
    description: `Given the root of a binary tree, return the inorder traversal of its nodes\' values.\n\nInorder traversal visits: left subtree → root → right subtree.`,
    examples: [
      { input: 'root = [1,null,2,3]', output: '[1,3,2]' },
      { input: 'root = [1]', output: '[1]' }
    ],
    constraints: 'The number of nodes in the tree is in range [0, 100].',
    solution_template: '#include <iostream>\n#include <vector>\nusing namespace std;\n\nstruct TreeNode {\n    int val;\n    TreeNode *left, *right;\n    TreeNode(int x) : val(x), left(nullptr), right(nullptr) {}\n};\n\nvoid inorder(TreeNode* root, vector<int>& result) {\n    // Write inorder traversal here\n}\n\nint main() {\n    TreeNode* root = new TreeNode(1);\n    root->right = new TreeNode(2);\n    root->right->left = new TreeNode(3);\n    vector<int> result;\n    inorder(root, result);\n    for (int v : result) cout << v << " ";\n    cout << endl;\n    return 0;\n}',
    test_cases: [
      { input: '', expected: '1 3 2' }
    ]
  },
  {
    id: 'prob-09', title: 'Maximum Subarray', difficulty: 'medium', category: 'arrays',
    description: `Given an integer array \`nums\`, find the subarray with the largest sum, and return its sum.\n\nThis is Kadane\'s algorithm.`,
    examples: [
      { input: 'nums = [-2,1,-3,4,-1,2,1,-5,4]', output: '6', explanation: 'The subarray [4,-1,2,1] has the largest sum 6.' },
      { input: 'nums = [1]', output: '1' },
      { input: 'nums = [5,4,-1,7,8]', output: '23' }
    ],
    constraints: '1 <= nums.length <= 10^5, -10^4 <= nums[i] <= 10^4',
    solution_template: '#include <iostream>\n#include <vector>\nusing namespace std;\n\nint maxSubArray(vector<int>& nums) {\n    // Write Kadane\'s algorithm\n    return 0;\n}\n\nint main() {\n    vector<int> nums = {-2, 1, -3, 4, -1, 2, 1, -5, 4};\n    cout << maxSubArray(nums) << endl;\n    return 0;\n}',
    test_cases: [
      { input: '', expected: '6' }
    ]
  },
  {
    id: 'prob-10', title: 'Climbing Stairs', difficulty: 'easy', category: 'dp',
    description: `You are climbing a staircase. It takes \`n\` steps to reach the top.\n\nEach time you can either climb 1 or 2 steps. In how many distinct ways can you climb to the top?\n\nThis is essentially the Fibonacci sequence.`,
    examples: [
      { input: 'n = 2', output: '2', explanation: '1 step + 1 step, 2 steps' },
      { input: 'n = 3', output: '3', explanation: '1+1+1, 1+2, 2+1' }
    ],
    constraints: '1 <= n <= 45',
    solution_template: '#include <iostream>\nusing namespace std;\n\nint climbStairs(int n) {\n    // Write your DP solution\n    return 0;\n}\n\nint main() {\n    int n = 10;\n    cout << climbStairs(n) << endl;\n    return 0;\n}',
    test_cases: [
      { input: '', expected: '89' }
    ]
  },
  {
    id: 'prob-11', title: 'Reverse Linked List', difficulty: 'easy', category: 'linked-list',
    description: `Given the head of a singly linked list, reverse the list, and return the reversed list.`,
    examples: [
      { input: 'head = [1,2,3,4,5]', output: '[5,4,3,2,1]' },
      { input: 'head = [1,2]', output: '[2,1]' }
    ],
    constraints: 'The number of nodes is in range [0, 5000].',
    solution_template: '#include <iostream>\nusing namespace std;\n\nstruct ListNode {\n    int val;\n    ListNode *next;\n    ListNode(int x) : val(x), next(nullptr) {}\n};\n\nListNode* reverseList(ListNode* head) {\n    // Write reverse linked list\n    return nullptr;\n}\n\nvoid printList(ListNode* head) {\n    while (head) { cout << head->val << " "; head = head->next; }\n    cout << endl;\n}\n\nint main() {\n    ListNode* head = new ListNode(1);\n    head->next = new ListNode(2);\n    head->next->next = new ListNode(3);\n    head->next->next->next = new ListNode(4);\n    head->next->next->next->next = new ListNode(5);\n    ListNode* reversed = reverseList(head);\n    printList(reversed);\n    return 0;\n}',
    test_cases: [
      { input: '', expected: '5 4 3 2 1' }
    ]
  },
  {
    id: 'prob-12', title: 'Merge Sorted Arrays', difficulty: 'easy', category: 'arrays',
    description: `You are given two integer arrays \`nums1\` and \`nums2\`, sorted in non-decreasing order. Merge \`nums2\` into \`nums1\` as one sorted array.`,
    examples: [
      { input: 'nums1 = [1,2,3,0,0,0], m=3, nums2 = [2,5,6], n=3', output: '[1,2,2,3,5,6]' }
    ],
    constraints: 'nums1.length == m + n, nums2.length == n',
    solution_template: '#include <iostream>\n#include <vector>\nusing namespace std;\n\nvoid merge(vector<int>& nums1, int m, vector<int>& nums2, int n) {\n    // Write merge here (start from the end!)\n}\n\nint main() {\n    vector<int> nums1 = {1,2,3,0,0,0};\n    vector<int> nums2 = {2,5,6};\n    merge(nums1, 3, nums2, 3);\n    for (int x : nums1) cout << x << " ";\n    cout << endl;\n    return 0;\n}',
    test_cases: [
      { input: '', expected: '1 2 2 3 5 6' }
    ]
  }
];

const existingExtraLessons = [
  // ===== FUNCTIONS (continued) =====
  {
    id: 'lesson-12', title: 'Function Overloading & Default Args', category: 'functions', order_index: 12,
    content: '## Default Arguments\n\nAllow calling a function with fewer arguments by providing default values:\n\n```cpp\nvoid display(const string& name, int age = 18, double height = 5.5) {\n    cout << name << ", " << age << ", " << height;\n}\n\ndisplay("Alice");           // Uses defaults\ndisplay("Bob", 25);         // Custom age\ndisplay("Charlie", 30, 6.1); // All custom\n```\n\n### Rules\n1. Defaults must be at the END of the parameter list\n2. Once a parameter has a default, ALL subsequent parameters must also have defaults\n3. Defaults are specified in the **declaration**, not the definition\n\n## Function Overloading\n\nMultiple functions with the **same name** but **different parameters**:\n\n```cpp\nvoid print(int i)      { cout << "Integer: " << i; }\nvoid print(double d)  { cout << "Double: " << d; }\nvoid print(string s)  { cout << "String: " << s; }\n```\n\n### Overload Resolution\n1. Exact match\n2. Promotion (float → double, int → long)\n3. Standard conversion (int → double)\n\n### Ambiguity\n```cpp\nvoid f(int x)    { }\nvoid f(double x) { }\nf(\'A\');   // Ambiguous! Both are equally valid\n```\n\n## Best Practices\n1. Use overloading for functions doing the same conceptual operation\n2. Be careful with default arguments and overloading together',
    code_example: '#include <iostream>\nusing namespace std;\n\ndouble area(double r) { return 3.14159 * r * r; }  // Circle\ndouble area(double l, double w) { return l * w; }  // Rectangle\n\nvoid greet(const string& name, const string& greeting = "Hello") {\n    cout << greeting << ", " << name << "!" << endl;\n}\n\nint main() {\n    cout << "Circle r=5: " << area(5.0) << endl;\n    cout << "Rect 4x6: " << area(4.0, 6.0) << endl;\n    greet("Alice");\n    greet("Bob", "Hi");\n    return 0;\n}'
  },
  {
    id: 'lesson-13', title: 'Recursion', category: 'functions', order_index: 13,
    content: '## What is Recursion?\n\nA recursive function is one that calls itself. It breaks problems into smaller, similar subproblems.\n\n## Anatomy\nEvery recursive function needs:\n1. **Base case**: When to stop\n2. **Recursive case**: Call itself with smaller input\n\n```cpp\nint factorial(int n) {\n    if (n <= 1) return 1;          // Base case\n    return n * factorial(n - 1);    // Recursive case\n}\n```\n\n## How It Works: The Call Stack\n```\nfactorial(4) = 4 * factorial(3)\n  factorial(3) = 3 * factorial(2)\n    factorial(2) = 2 * factorial(1)\n      factorial(1) = 1  ← Base case\n    factorial(2) = 2\n  factorial(3) = 6\nfactorial(4) = 24\n```\n\n## Classic Problems\n\n### Fibonacci\n```cpp\nint fib(int n) {\n    if (n <= 1) return n;\n    return fib(n - 1) + fib(n - 2);\n}\n```\n\n### Palindrome\n```cpp\nbool isPalindrome(const string& s, int start, int end) {\n    if (start >= end) return true;\n    if (s[start] != s[end]) return false;\n    return isPalindrome(s, start + 1, end - 1);\n}\n```\n\n## Tail Recursion\nRecursive call is the LAST thing the function does — compiler can optimize to a loop.\n\n## Recursion vs Iteration\n| Aspect | Recursion | Iteration |\n|--------|-----------|-----------|\n| Stack usage | O(depth) | O(1) |\n| Performance | Call overhead | Faster |\n| Best for | Trees, divide-conquer | Linear ops |\n\n## Pitfalls\n1. Missing base case → stack overflow\n2. No progress toward base case\n3. Exponential complexity (use memoization!)',
    code_example: '#include <iostream>\nusing namespace std;\n\nint factorial(int n) {\n    if (n <= 1) return 1;\n    return n * factorial(n - 1);\n}\n\nint fib(int n) {\n    if (n <= 1) return n;\n    return fib(n-1) + fib(n-2);\n}\n\nint arraySum(int arr[], int n) {\n    if (n <= 0) return 0;\n    return arr[n-1] + arraySum(arr, n-1);\n}\n\nint main() {\n    cout << "5! = " << factorial(5) << endl;\n    cout << "fib(10) = " << fib(10) << endl;\n    int arr[] = {3, 7, 2, 9, 5};\n    cout << "Sum = " << arraySum(arr, 5) << endl;\n    return 0;\n}'
  },
  {
    id: 'lesson-14', title: 'Lambda Expressions', category: 'functions', order_index: 14,
    content: '## What are Lambdas?\n\nLambdas (C++11) are anonymous functions — define them inline, right where needed.\n\n## Syntax\n```cpp\n[capture](parameters) -> return_type { body };\n\nauto square = [](int x) -> int { return x * x; };\ncout << square(5);  // 25\n```\n\nReturn type can be omitted:\n```cpp\nauto square = [](int x) { return x * x; };\n```\n\n## Capture Clause\n\n### By Value (=)\n```cpp\nint m = 3;\nauto times = [=](int x) { return x * m; };\n```\n\n### By Reference (&)\n```cpp\nint counter = 0;\nauto inc = [&counter]() { counter++; };\n```\n\n### Mixed\n```cpp\n[=, &c]()   // Everything by value, c by reference\n[&, a]()    // Everything by reference, a by value\n```\n\n## Lambdas with STL Algorithms\n\n```cpp\nvector<int> nums = {5, 2, 8, 1, 9};\n\n// Sort descending\nsort(nums.begin(), nums.end(), [](int a, int b) { return a > b; });\n\n// Filter\nint evenCount = count_if(nums.begin(), nums.end(), [](int x) { return x % 2 == 0; });\n\n// Transform\ntransform(nums.begin(), nums.end(), nums.begin(), [](int x) { return x * 2; });\n```\n\n## Generic Lambdas (C++14)\n```cpp\nauto add = [](auto a, auto b) { return a + b; };\ncout << add(5, 3);     // int\ncout << add(2.5, 1.5); // double\n```\n\n## std::function\nStore any callable:\n```cpp\nfunction<int(int, int)> op;\nop = [](int a, int b) { return a + b; };\nop = [](int a, int b) { return a * b; };\n```\n\n## Best Practices\n1. Keep lambdas short\n2. Prefer [&] for efficiency\n3. Avoid capturing by reference if lambda outlives capture scope',
    code_example: '#include <iostream>\n#include <vector>\n#include <algorithm>\n#include <functional>\nusing namespace std;\n\nint main() {\n    vector<int> nums = {7, 2, 9, 1, 5, 3, 8, 4, 6};\n\n    sort(nums.begin(), nums.end(), [](int a, int b) { return a < b; });\n    cout << "Sorted: ";\n    for (int n : nums) cout << n << " "; cout << endl;\n\n    auto evenCount = count_if(nums.begin(), nums.end(), [](int x) { return x % 2 == 0; });\n    cout << "Evens: " << evenCount << endl;\n\n    function<int(int, int)> op = [](int a, int b) { return a + b; };\n    cout << "5 + 3 = " << op(5, 3) << endl;\n\n    return 0;\n}'
  },
  {
    id: 'lesson-15', title: 'Function Pointers & Callbacks', category: 'functions', order_index: 15,
    content: '## Function Pointers\n\nA function pointer stores the address of a function, enabling callbacks and dynamic dispatch.\n\n## Declaration\n```cpp\nint add(int a, int b) { return a + b; }\n\nint (*funcPtr)(int, int);  // Pointer to function taking two ints, returning int\nfuncPtr = &add;\n\nint result = funcPtr(5, 3);  // 8\n```\n\n### Cleaner Syntax with using\n```cpp\nusing BinaryOp = int (*)(int, int);\nBinaryOp op = add;\n```\n\n## Callbacks\nPass a function as an argument:\n```cpp\nvoid sortArray(int arr[], int n, bool (*compare)(int, int)) {\n    // Use compare to determine order\n}\n\nbool ascending(int a, int b) { return a > b; }\nbool descending(int a, int b) { return a < b; }\n\nsortArray(arr, 5, ascending);\nsortArray(arr, 5, descending);\n```\n\n## std::function (Modern C++)\nCan hold any callable (function, lambda, functor):\n```cpp\nfunction<int(int, int)> func;\nfunc = add;                    // Regular function\nfunc = [](int a, int b) { return a * b; };  // Lambda\n```\n\n## Function Pointer vs std::function\n| Aspect | Function Pointer | std::function |\n|--------|-----------------|---------------|\n| Overhead | Minimal | Slightly more |\n| Flexibility | Only functions | Any callable |\n| Syntax | Complex | Clean |\n\n## Use Cases\n1. Event handling ("call when button clicked")\n2. Custom sorting/comparison\n3. Strategy pattern — interchangeable algorithms\n4. Asynchronous operations',
    code_example: '#include <iostream>\n#include <functional>\n#include <vector>\nusing namespace std;\n\nint add(int a, int b) { return a + b; }\nint sub(int a, int b) { return a - b; }\nint mul(int a, int b) { return a * b; }\n\nint apply(int a, int b, function<int(int,int)> op) {\n    return op(a, b);\n}\n\nint main() {\n    vector<function<int(int,int)>> ops = {add, sub, mul};\n    vector<string> names = {"add", "sub", "mul"};\n    for (size_t i = 0; i < ops.size(); i++) {\n        cout << names[i] << "(10,5) = " << apply(10, 5, ops[i]) << endl;\n    }\n    return 0;\n}'
  },

  // ===== ARRAYS =====
  {
    id: 'lesson-16', title: 'Arrays', category: 'arrays', order_index: 16,
    content: '## What is an Array?\n\nAn array is a collection of elements of the SAME type stored in contiguous memory. Arrays provide O(1) random access.\n\n## Declaration and Initialization\n```cpp\nint numbers[5];           // Uninitialized — garbage values\nint scores[5] = {90, 85, 78, 92, 88};  // Full init\nint zeros[5] = {0};                    // All zeros\nint values[] = {1, 2, 3, 4, 5};        // Size deduced (5)\n```\n\n## Accessing Elements\nIndex starts at 0:\n```cpp\nint arr[5] = {10, 20, 30, 40, 50};\ncout << arr[0];  // 10\narr[2] = 35;     // Modify\n```\n\n## Memory Layout\n```\nIndex:  | 0  | 1  | 2  | 3  | 4  |\nValue:  | 10 | 20 | 30 | 40 | 50 |\nAddress:| 100| 104| 108| 112| 116|  (int = 4 bytes)\n```\n\n`arr[i]` is equivalent to `*(arr + i)` — pointer arithmetic.\n\n## Multi-dimensional Arrays\n```cpp\nint matrix[3][4] = {\n    {1, 2, 3, 4},\n    {5, 6, 7, 8},\n    {9, 10, 11, 12}\n};\ncout << matrix[1][2];  // 7\n```\n\n## Array Size\n```cpp\nint arr[] = {1, 2, 3, 4, 5};\nint size = sizeof(arr) / sizeof(arr[0]);  // 5\n```\n\n**Warning**: When passed to a function, array "decays" to a pointer — size information is lost. Always pass size separately.\n\n## Limitations\n1. Fixed compile-time size\n2. No bounds checking (`arr[10]` in 5-element array = UB)\n3. Size info lost when passed to functions\n4. Can\'t copy or assign directly\n\nThese limitations are why C++ provides `std::vector` and `std::array`.',
    code_example: '#include <iostream>\nusing namespace std;\n\nint main() {\n    int marks[] = {85, 92, 78, 90, 88};\n    int n = sizeof(marks) / sizeof(marks[0]);\n\n    cout << "Marks: ";\n    for (int i = 0; i < n; i++) cout << marks[i] << " ";\n    cout << endl;\n\n    int max = marks[0];\n    for (int i = 1; i < n; i++) if (marks[i] > max) max = marks[i];\n    cout << "Highest: " << max << endl;\n\n    int grid[3][3] = {{1,2,3},{4,5,6},{7,8,9}};\n    for (int i = 0; i < 3; i++) {\n        for (int j = 0; j < 3; j++) cout << grid[i][j] << " ";\n        cout << endl;\n    }\n    return 0;\n}'
  },
  {
    id: 'lesson-17', title: 'C-Strings & String Functions', category: 'arrays', order_index: 17,
    content: '## C-Strings (Null-Terminated Strings)\n\nC-strings are arrays of characters ending with null character `\\0`.\n\n```cpp\nchar greeting[] = "Hello";  // Stores: \'H\',\'e\',\'l\',\'l\',\'o\',\'\\0\'\n```\n\n## Common Functions (<cstring>)\n| Function | Description |\n|----------|-------------|\n| `strlen(s)` | Length excluding null |\n| `strcpy(dst, src)` | Copy (dangerous — no bounds check!) |\n| `strncpy(dst, src, n)` | Copy at most n chars |\n| `strcat(dst, src)` | Append src to dst |\n| `strcmp(s1, s2)` | Compare (0 if equal) |\n| `strstr(s, sub)` | Find substring |\n| `strtok(s, delim)` | Tokenize (destructive!) |\n\n```cpp\nchar str1[50] = "Hello";\nchar str2[] = " World";\nstrcat(str1, str2);         // "Hello World"\ncout << strlen(str1);       // 11\n```\n\n## Buffer Overflow Danger\n```cpp\nchar buffer[5];\nstrcpy(buffer, "This is way too long!");  // OVERFLOW! UB!\n\n// Safer:\nstrncpy(buffer, "This is way too long!", sizeof(buffer) - 1);\nbuffer[sizeof(buffer) - 1] = \'\\0\';\n```\n\n## String to Number Conversion\n```cpp\n#include <cstdlib>\nint i = atoi("42");\ndouble d = atof("3.14");\nlong val = strtol("42abc", &end, 10);  // val=42, with error checking\n```\n\n## Why Prefer std::string\n- Error-prone (overflows, null termination)\n- Inconvenient (no + operator)\n- Unsafe (no bounds checking)\n\nModern C++ strongly recommends `std::string` over C-strings.',
    code_example: '#include <iostream>\n#include <cstring>\nusing namespace std;\n\nint main() {\n    char name[50] = "John";\n    char lastName[] = " Doe";\n    strcat(name, lastName);\n    cout << "Full: " << name << endl;\n    cout << "Length: " << strlen(name) << endl;\n\n    char input[50];\n    cout << "Enter something: ";\n    cin >> input;\n    if (strcmp(input, "quit") == 0) cout << "Exiting" << endl;\n    else cout << "You entered: " << input << endl;\n\n    return 0;\n}'
  },
  {
    id: 'lesson-18', title: 'std::string', category: 'arrays', order_index: 18,
    content: '## The std::string Class\n\nModern, safe, convenient string type. Manages memory automatically.\n\n## Creating Strings\n```cpp\n#include <string>\nstring s1;                // Empty\nstring s2 = "Hello";\nstring s3(5, \'A\');         // "AAAAA"\nstring s4 = s2 + " World"; // Concatenation\n```\n\n## Common Operations\n\n### Size and Access\n```cpp\nstring s = "Hello";\ns.length();    // 5\ns.size();      // 5\ns[0];          // \'H\' (no bounds check)\ns.at(0);       // \'H\' (throws if invalid)\ns.front();     // \'H\'\ns.back();      // \'o\'\ns.c_str();     // const char*\n```\n\n### Modification\n```cpp\ns += " World";        // Append\ns.append("!");        // "Hello World!"\ns.insert(5, " cruel"); // "Hello cruel World!"\ns.erase(5, 6);        // "Hello World!"\ns.replace(6, 5, "Earth"); // "Hello Earth!"\ns.clear();            // ""\n```\n\n### Searching\n```cpp\ns.find("World");        // 6 (position)\ns.rfind(\'o\');           // 7 (last occurrence)\ns.find_first_of("aeiou"); // 1 (\'e\')\n\nif (s.find("xyz") == string::npos) {\n    // Not found!\n}\n```\n\n### Conversion\n```cpp\nint i = stoi("42");\ndouble d = stod("3.14");\nstring s = to_string(42);  // "42"\n```\n\n## Performance Tips\n1. Pass by const string& to avoid copying\n2. Use reserve() if you know final size\n3. s += c is faster than s = s + c',
    code_example: '#include <iostream>\n#include <string>\n#include <sstream>\nusing namespace std;\n\nint main() {\n    string greeting = "Hello";\n    string name = "Alice";\n    string full = greeting + ", " + name + "!";\n    cout << full << " (length: " << full.length() << ")" << endl;\n\n    size_t pos = full.find("Alice");\n    if (pos != string::npos) cout << "Found at " << pos << endl;\n\n    full.replace(7, 5, "Bob");\n    cout << "Replaced: " << full << endl;\n\n    stringstream ss;\n    ss << "Answer: " << 42 << \", Pi: " << 3.14;\n    cout << ss.str() << endl;\n\n    return 0;\n}'
  },
  {
    id: 'lesson-19', title: 'Array Algorithms', category: 'arrays', order_index: 19,
    content: '## Fundamental Array Algorithms\n\n### 1. Linear Search\n```cpp\nint linearSearch(int arr[], int n, int target) {\n    for (int i = 0; i < n; i++)\n        if (arr[i] == target) return i;\n    return -1;\n}\n// Time: O(n), Space: O(1)\n```\n\n### 2. Binary Search (Sorted Array)\n```cpp\nint binarySearch(int arr[], int n, int target) {\n    int left = 0, right = n - 1;\n    while (left <= right) {\n        int mid = left + (right - left) / 2;\n        if (arr[mid] == target) return mid;\n        if (arr[mid] < target) left = mid + 1;\n        else right = mid - 1;\n    }\n    return -1;\n}\n// Time: O(log n), Space: O(1)\n```\n\n### 3. Two-Pointer Technique\n```cpp\n// Find if sorted array has two numbers summing to target\nbool twoSum(int arr[], int n, int target) {\n    int left = 0, right = n - 1;\n    while (left < right) {\n        int sum = arr[left] + arr[right];\n        if (sum == target) return true;\n        if (sum < target) left++;\n        else right--;\n    }\n    return false;\n}\n// Time: O(n)\n```\n\n### 4. Prefix Sum\n```cpp\nint prefix[n];\nprefix[0] = arr[0];\nfor (int i = 1; i < n; i++)\n    prefix[i] = prefix[i-1] + arr[i];\n\n// Sum arr[l] to arr[r] in O(1):\nint rangeSum(int l, int r) {\n    if (l == 0) return prefix[r];\n    return prefix[r] - prefix[l - 1];\n}\n```\n\n### 5. Sliding Window\n```cpp\n// Max sum of subarray of size k\nint maxSumSubarray(int arr[], int n, int k) {\n    int sum = 0;\n    for (int i = 0; i < k; i++) sum += arr[i];\n    int maxSum = sum;\n    for (int i = k; i < n; i++) {\n        sum += arr[i] - arr[i - k];\n        maxSum = max(maxSum, sum);\n    }\n    return maxSum;\n}\n// Time: O(n)\n```\n\n### 6. Kadane\'s Algorithm (Max Subarray Sum)\n```cpp\nint maxSubarraySum(int arr[], int n) {\n    int maxEnd = arr[0], maxSoFar = arr[0];\n    for (int i = 1; i < n; i++) {\n        maxEnd = max(arr[i], maxEnd + arr[i]);\n        maxSoFar = max(maxSoFar, maxEnd);\n    }\n    return maxSoFar;\n}\n// Time: O(n)\n```',
    code_example: '#include <iostream>\nusing namespace std;\n\nint binarySearch(int arr[], int n, int target) {\n    int l = 0, r = n - 1;\n    while (l <= r) {\n        int m = l + (r - l) / 2;\n        if (arr[m] == target) return m;\n        if (arr[m] < target) l = m + 1;\n        else r = m - 1;\n    }\n    return -1;\n}\n\nint maxSubarraySum(int arr[], int n) {\n    int maxEnd = arr[0], maxSF = arr[0];\n    for (int i = 1; i < n; i++) {\n        maxEnd = max(arr[i], maxEnd + arr[i]);\n        maxSF = max(maxSF, maxEnd);\n    }\n    return maxSF;\n}\n\nint main() {\n    int arr[] = {1, 3, 5, 7, 9, 11};\n    int n = sizeof(arr)/sizeof(arr[0]);\n    cout << "7 at index: " << binarySearch(arr, n, 7) << endl;\n\n    int nums[] = {-2, 1, -3, 4, -1, 2, 1, -5, 4};\n    cout << "Max subarray: " << maxSubarraySum(nums, 9) << endl;\n    return 0;\n}'
  },
  {
    id: 'lesson-20', title: 'Vectors (std::vector)', category: 'arrays', order_index: 20,
    content: '## What is std::vector?\n\nA dynamic array that grows and shrinks automatically. The most commonly used container in C++.\n\n## Creating Vectors\n```cpp\n#include <vector>\nvector<int> v1;                // Empty\nvector<int> v2(10);            // 10 elements (0-initialized)\nvector<int> v3(5, 42);         // 5 elements, all 42\nvector<int> v4 = {1, 2, 3, 4, 5};  // Initializer list\n```\n\n## Element Access\n```cpp\nv[0];        // No bounds check\nv.at(2);     // Throws out_of_range if invalid\nv.front();   // First element\nv.back();    // Last element\nv.data();    // Raw pointer to underlying array\n```\n\n## Adding and Removing\n```cpp\nv.push_back(10);    // Add to end\nv.pop_back();       // Remove last\nv.insert(v.begin() + 1, 15);  // Insert at position\nv.erase(v.begin() + 2);       // Remove at position\nv.clear();          // Remove all\n```\n\n## Size and Capacity\n```cpp\nv.size();       // Number of elements\nv.capacity();   // Allocated storage (>= size)\nv.empty();      // Check if empty\nv.reserve(100); // Pre-allocate capacity\nv.shrink_to_fit(); // Reduce capacity to fit size\n```\n\nWhen a vector runs out of capacity, it typically doubles in size (O(1) amortized push_back).\n\n## Iterating\n```cpp\nfor (int x : v) { }                      // Range-based\nfor (size_t i = 0; i < v.size(); i++) { } // Index\nfor (auto it = v.begin(); it != v.end(); ++it) { } // Iterator\n```\n\n## Common Operations\n```cpp\nsort(v.begin(), v.end());\nreverse(v.begin(), v.end());\nfind(v.begin(), v.end(), 42);\n// Erase-remove idiom:\nv.erase(remove(v.begin(), v.end(), 42), v.end());\n```\n\n## 2D Vectors\n```cpp\nvector<vector<int>> grid(3, vector<int>(4, 0));\n```\n\n## Performance Tips\n1. Use reserve() if you know final size\n2. Prefer push_back over insert at beginning\n3. Use emplace_back() for complex objects\n4. Pass by const vector& to avoid copying',
    code_example: '#include <iostream>\n#include <vector>\n#include <algorithm>\nusing namespace std;\n\nint main() {\n    vector<int> nums = {5, 2, 8, 1, 9, 3, 7, 4, 6};\n\n    nums.push_back(10);\n    sort(nums.begin(), nums.end());\n\n    cout << "Sorted: ";\n    for (int n : nums) cout << n << " "; cout << endl;\n\n    vector<vector<int>> matrix = {{1,2,3},{4,5,6},{7,8,9}};\n    cout << "Matrix:" << endl;\n    for (auto& row : matrix) {\n        for (int val : row) cout << val << " ";\n        cout << endl;\n    }\n\n    cout << "Size: " << nums.size() << ", Cap: " << nums.capacity() << endl;\n    return 0;\n}'
  },

  // ===== POINTERS =====
  {
    id: 'lesson-21', title: 'Pointers', category: 'pointers', order_index: 21,
    content: '## What is a Pointer?\n\nA pointer stores the memory address of another variable. It "points to" where the value is stored.\n\n## Address-of Operator (&)\n```cpp\nint x = 42;\ncout << &x;  // Prints address like 0x7ffd5a8b4c34\n```\n\n## Declaring and Using Pointers\n```cpp\nint x = 42;\nint* ptr = &x;   // ptr holds the address of x\n\ncout << *ptr;    // 42 (dereference — get value at address)\n*ptr = 100;      // Modify x through pointer\ncout << x;       // 100!\n```\n\n## Null Pointers\n```cpp\nint* ptr = nullptr;  // Points to nothing\nif (ptr != nullptr) {\n    cout << *ptr;     // Safe to dereference\n}\n```\n\nDereferencing nullptr = undefined behavior (crash).\n\n## Pointer Arithmetic\n```cpp\nint arr[] = {10, 20, 30, 40, 50};\nint* p = arr;         // Points to arr[0]\n\ncout << *p;           // 10\ncout << *(p + 1);     // 20 (moves 4 bytes forward)\np++;                  // Now points to arr[1]\n```\n\n## Pointers and Arrays\n```cpp\narr[2] == *(arr + 2)  // True!\narr == &arr[0]        // True!\n```\n\n## Pointers to Pointers\n```cpp\nint x = 42;\nint* p = &x;\nint** pp = &p;   // Points to p\ncout << **pp;    // 42\n```\n\n## Common Mistakes\n1. Uninitialized pointer — `int* p; *p = 42;` UB!\n2. Dangling pointer — using after `delete`\n3. Memory leak — not calling `delete`\n4. Buffer overflow — writing past array end\n\n## When to Use Pointers\n1. Dynamic memory allocation\n2. Data structures (linked lists, trees)\n3. Polymorphism\n4. Working with C-style APIs',
    code_example: '#include <iostream>\nusing namespace std;\n\nint main() {\n    int x = 42;\n    int* ptr = &x;\n\n    cout << "x = " << x << ", addr = " << &x << endl;\n    cout << "ptr holds " << ptr << ", *ptr = " << *ptr << endl;\n\n    *ptr = 100;\n    cout << "After *ptr = 100, x = " << x << endl;\n\n    int arr[] = {10, 20, 30, 40, 50};\n    int* p = arr;\n    for (int i = 0; i < 5; i++)\n        cout << "arr[" << i << "] = " << *(p + i) << endl;\n\n    int* safe = nullptr;\n    if (safe) cout << *safe;  // Won\'t execute\n    else cout << "Null pointer safe" << endl;\n\n    return 0;\n}'
  },
  {
    id: 'lesson-22', title: 'Dynamic Memory', category: 'pointers', order_index: 22,
    content: '## Stack vs Heap\n\n| Aspect | Stack | Heap |\n|--------|-------|------|\n| Size | Small (few MB) | Large (GB) |\n| Speed | Very fast | Slower |\n| Allocation | Automatic | Manual (new/delete) |\n| Lifetime | Scope-based | Until deleted |\n\n## new and delete\n```cpp\nint* p = new int;       // Uninitialized\nint* p = new int(42);   // Initialized to 42\n\ndelete p;               // FREE the memory!\np = nullptr;            // Good practice\n```\n\n## Dynamic Arrays\n```cpp\nint* arr = new int[10];\narr[0] = 1;\n// ... use it ...\ndelete[] arr;  // Note the []!\n```\n\n## malloc/free (C-style)\n```cpp\nint* arr = (int*)malloc(10 * sizeof(int));\nfree(arr);\n```\n\n**Prefer new/delete over malloc/free** — new calls constructors.\n\n## Memory Leaks\n```cpp\nvoid leak() {\n    int* p = new int(42);\n    // Never deleted! 4 bytes leaked.\n}\n\nfor (int i = 0; i < 1000; i++) {\n    int* p = new int[1000];  // 4 MB leaked per iteration!\n}\n```\n\n## Dangling Pointers\n```cpp\nint* p = new int(42);\ndelete p;\n*p = 10;  // UNDEFINED BEHAVIOR! p is dangling!\n```\n\n## RAII (Resource Acquisition Is Initialization)\nMost important C++ concept — resource lifetime tied to object lifetime:\n```cpp\nclass IntArray {\n    int* data;\npublic:\n    IntArray(int n) { data = new int[n]; }\n    ~IntArray() { delete[] data; }  // Auto-called!\n};\n\n{ IntArray arr(1000); }  // Auto-freed at scope end\n```\n\n## Smart Pointers (C++11) — Prefer These\n```cpp\nunique_ptr<int> p = make_unique<int>(42);  // Exclusive ownership\nshared_ptr<int> p = make_shared<int>(42);  // Shared ownership\n```\n\n## Best Practices\n1. Every new → matching delete\n2. Every new[] → matching delete[]\n3. Set pointers to nullptr after delete\n4. Prefer smart pointers over raw new/delete\n5. Use containers (vector, string) instead of manual arrays',
    code_example: '#include <iostream>\nusing namespace std;\n\nint main() {\n    int* p = new int(42);\n    cout << "Dynamic int: " << *p << endl;\n    delete p;\n\n    int n;\n    cout << "Array size: ";\n    cin >> n;\n    int* arr = new int[n];\n    cout << "Enter " << n << " numbers: ";\n    for (int i = 0; i < n; i++) cin >> arr[i];\n    cout << "You entered: ";\n    for (int i = 0; i < n; i++) cout << arr[i] << " ";\n    cout << endl;\n    delete[] arr;\n\n    return 0;\n}'
  },
  {
    id: 'lesson-23', title: 'References vs Pointers', category: 'pointers', order_index: 23,
    content: '## What is a Reference?\n\nA reference is an alias (alternative name) for an existing variable. Once bound, it cannot be changed.\n\n```cpp\nint x = 42;\nint& ref = x;    // ref is a reference to x\nref = 100;        // Same as x = 100\ncout << x;        // 100\n```\n\n## References vs Pointers\n| Aspect | Reference | Pointer |\n|--------|-----------|---------|\n| Initialization | Must init when declared | Can be uninitialized |\n| Reassignment | Cannot change target | Can point elsewhere |\n| Null | Cannot be null | Can be nullptr |\n| Syntax | ref (direct) | *p (dereference) |\n| Arithmetic | No | Yes |\n\n## Pass by Reference\n```cpp\nvoid swap(int& a, int& b) {\n    int temp = a;\n    a = b;\n    b = temp;\n}\n```\n\n## Const References (Most Common)\nPass large objects without copying or modifying:\n```cpp\nvoid printData(const vector<int>& data) {\n    for (int x : data) cout << x;\n}\n```\n\n## Return by Reference\n```cpp\nint& getElement(int arr[], int index) {\n    return arr[index];\n}\ngetElement(arr, 2) = 42;  // Modifies arr[2]!\n```\n\n## Rvalue References (C++11)\n```cpp\nvoid foo(int& x)  { }  // L-value reference\nvoid foo(int&& x) { }  // R-value reference (temporaries)\n\nint a = 5;\nfoo(a);    // Calls foo(int&)\nfoo(10);   // Calls foo(int&&)\n```\n\n## When to Use What\n| Situation | Use |\n|-----------|-----|\n| Input param, no copy | const T& |\n| Output param | T& |\n| Optional/nullable param | T* |\n| Pointer arithmetic | T* |\n| Data structures | T* or smart ptr |\n\n## Common Mistakes\n```cpp\n// Returning reference to local variable\nint& bad() {\n    int x = 42;\n    return x;  // BAD — x destroyed after return!\n}\n\n// Trying to reassign reference\nint a = 1, b = 2;\nint& ref = a;\nref = b;  // Sets a = 2, NOT makes ref refer to b!\n```',
    code_example: '#include <iostream>\n#include <vector>\nusing namespace std;\n\nvoid square(int& x) { x = x * x; }\n\nvoid display(const vector<int>& v) {\n    for (int x : v) cout << x << " "; cout << endl;\n}\n\nint& getLast(vector<int>& v) { return v.back(); }\n\nint main() {\n    int value = 5;\n    int& ref = value;\n    ref = 10;\n    cout << "value = " << value << endl;\n\n    int n = 7;\n    square(n);\n    cout << "7 squared = " << n << endl;\n\n    vector<int> data = {1,2,3,4,5};\n    getLast(data) = 100;\n    display(data);\n\n    return 0;\n}'
  },
  {
    id: 'lesson-24', title: 'Smart Pointers', category: 'pointers', order_index: 24,
    content: '## The Problem with Raw Pointers\n\nManual memory management is error-prone:\n- Memory leaks (forgetting delete)\n- Dangling pointers (using after delete)\n- Double deletion (deleting twice)\n\nSmart pointers automate memory management.\n\n## unique_ptr (Exclusive Ownership)\n\nOnly one pointer can own the object at a time. Cannot be copied, only moved.\n\n```cpp\n#include <memory>\nauto p1 = make_unique<int>(42);  // C++14 preferred\n// unique_ptr<int> p2 = p1;  // ERROR — no copy!\nauto p2 = move(p1);  // OK — transfer ownership\np1.reset();  // Delete owned object\n```\n\n## shared_ptr (Shared Ownership)\n\nReference counting — object deleted when last shared_ptr is destroyed.\n\n```cpp\nauto p1 = make_shared<int>(42);\n{\n    auto p2 = p1;  // Ref count = 2\n    auto p3 = p1;  // Ref count = 3\n}  // p2, p3 gone — count = 1\np1.reset();  // Object deleted — count = 0\n```\n\n### Circular References Problem\n```cpp\nstruct Node {\n    shared_ptr<Node> next;\n    shared_ptr<Node> prev;  // BAD — circular!\n};\n// Neither will ever be deleted!\n```\n\n## weak_ptr (Non-owning Observer)\nBreaks circular references:\n```cpp\nstruct Node {\n    shared_ptr<Node> next;\n    weak_ptr<Node> prev;  // No ownership\n};\n\nif (auto shared = prev.lock()) {\n    // Safe access\n}\n```\n\n## Factory Functions\nAlways prefer `make_unique`/`make_shared` over raw `new`:\n- Exception safety\n- Single allocation (shared_ptr)\n- Less typing\n\n## Smart Pointer Comparison\n| Feature | unique_ptr | shared_ptr | weak_ptr |\n|---------|------------|------------|----------|\n| Ownership | Exclusive | Shared | None |\n| Overhead | None | Reference counting | None |\n| Copy | Move only | Yes (ref++) | Yes |\n\n## Best Practices\n1. Use unique_ptr by default\n2. Use shared_ptr when ownership is truly shared\n3. Use weak_ptr to break circular references\n4. Never use raw new/delete in modern C++',
    code_example: '#include <iostream>\n#include <memory>\nusing namespace std;\n\nstruct Node {\n    int val;\n    shared_ptr<Node> next;\n    weak_ptr<Node> prev;\n    Node(int v) : val(v) { cout << "Node " << v << " created\\n"; }\n    ~Node() { cout << "Node " << val << " destroyed\\n"; }\n};\n\nint main() {\n    auto a = make_shared<Node>(1);\n    auto b = make_shared<Node>(2);\n    a->next = b;\n    b->prev = a;  // weak_ptr — no circular ref!\n\n    cout << "a use count: " << a.use_count() << endl;\n    cout << "b use count: " << b.use_count() << endl;\n\n    // Access weak_ptr\n    if (auto shared = b->prev.lock()) {\n        cout << "b->prev = " << shared->val << endl;\n    }\n\n    return 0;\n}  // Both auto-deleted\n'
  }
];

export function seedDatabase() {
  console.log('Seeding database...');

  const allLessons = [...lessons, ...existingExtraLessons, ...oopLessons, ...stlLessons, ...sortingLessons, ...linkedListLessons, ...treeLessons, ...advancedLessons];

  // Seed lessons
  for (const lesson of allLessons) {
    db.upsert('lessons', lesson.id, lesson);
  }
  console.log(`Seeded ${allLessons.length} lessons`);

  // Seed problems
  const allProblems = [
    ...problems,
    ...arrayProblems,
    ...stringProblems,
    ...linkedListProblems,
    ...treeProblems,
    ...stackQueueProblems,
    ...dpProblems,
    ...recursionProblems,
    ...graphProblems,
    ...binarySearchProblems,
    ...heapProblems,
    ...greedyProblems,
    ...sortingProblems,
    ...slidingWindowProblems,
    ...twoPointerProblems,
    ...bitManipulationProblems,
    ...mathsProblems,
    ...matrixProblems,
  ];
  for (const problem of allProblems) {
    db.upsert('problems', problem.id, {
      ...problem,
      examples: JSON.stringify(problem.examples),
      test_cases: JSON.stringify(problem.test_cases)
    });
  }
  console.log(`Seeded ${allProblems.length} problems`);

  console.log('Database seeded successfully!');
  return { lessons: allLessons.length, problems: problems.length };
}
