export default [
  // ========== BROAD CATEGORIES ==========
  {
    id: "arrays",
    name: "Arrays",
    type: "broad",
    description: "Problems involving contiguous memory blocks. Master indexing, traversal, subarray manipulation, and in-place operations.",
    when_to_use: "When order matters, you need fast index access, or the problem involves contiguous sequences of elements.",
    techniques: ["Two-pointer","Sliding Window","Prefix Sum","Kadane's Algorithm","Dutch National Flag"],
    difficulty: "Beginner to Advanced",
    icon: "[]",
    order: 1,
  },
  {
    id: "strings",
    name: "Strings",
    type: "broad",
    description: "Text processing problems: matching, rotation, palindrome checking, substring search, and character frequency analysis.",
    when_to_use: "When dealing with text, character sequences, or pattern matching within words.",
    techniques: ["Two-pointer","Sliding Window","Rabin-Karp","KMP","Trie","Frequency Map"],
    difficulty: "Beginner to Advanced",
    icon: "Aa",
    order: 2,
  },
  {
    id: "linked-list",
    name: "Linked Lists",
    type: "broad",
    description: "Node-based sequential structure. Master pointer manipulation, reversal, cycle detection, and merging.",
    when_to_use: "When frequent insertions/deletions are needed, size may grow dynamically, or circular/cyclic structures.",
    techniques: ["Slow-Fast Pointer","Dummy Node","Recursive Reversal","Runner Technique"],
    difficulty: "Intermediate",
    icon: "->",
    order: 3,
  },
  {
    id: "stack-queue",
    name: "Stacks & Queues",
    type: "broad",
    categories: ["stack-queue", "stacks"],
    description: "LIFO/FIFO structures essential for expression evaluation, monotonic patterns, BFS/DFS, and undo operations.",
    when_to_use: "When order of processing depends on nesting (stack) or level-order (queue), nearest greater/smaller elements.",
    techniques: ["Monotonic Stack","Deque","Two Queues/Stacks","Circular Buffer"],
    difficulty: "Intermediate",
    icon: "||",
    order: 4,
  },
  {
    id: "trees",
    name: "Trees",
    type: "broad",
    description: "Hierarchical data structures. Master traversals (inorder/preorder/postorder/level-order), BSTs, and recursion.",
    when_to_use: "Hierarchical data, binary search trees, expression trees, decision trees, or any parent-child relationship.",
    techniques: ["Recursive DFS","Iterative DFS (Stack)","BFS / Level Order","Morris Traversal","LCA"],
    difficulty: "Intermediate to Advanced",
    icon: "^Y",
    order: 5,
  },
  {
    id: "graphs",
    name: "Graphs",
    type: "broad",
    description: "Nodes connected by edges. Model networks, relationships, paths, and dependencies with traversal and shortest-path algorithms.",
    when_to_use: "Networks, paths, connectivity, dependency resolution, shortest path, cycles, or topological ordering.",
    techniques: ["DFS","BFS","Dijkstra","Union-Find","Topological Sort","Floyd-Warshall","Bellman-Ford"],
    difficulty: "Advanced",
    icon: "/\\",
    order: 6,
  },
  {
    id: "dp",
    name: "Dynamic Programming",
    type: "broad",
    description: "Break problems into overlapping subproblems, solve each once, and store results. Optimized recursion with memoization/tabulation.",
    when_to_use: "Optimal substructure, overlapping subproblems, counting/optimization — Fibonacci, knapsack, LCS, matrix chain.",
    techniques: ["Memoization (Top-Down)","Tabulation (Bottom-Up)","1D/2D DP","Knapsack","LCS/LIS","DP on Trees"],
    difficulty: "Advanced",
    icon: "DP",
    order: 7,
  },
  {
    id: "recursion",
    name: "Recursion & Backtracking",
    type: "broad",
    description: "Functions calling themselves. Essential for divide & conquer, permutations, subsets, and exhaustive search (backtracking).",
    when_to_use: "Problems with clear self-similar structure: tree traversals, combinatorial generation, N-Queens, Sudoku, maze solving.",
    techniques: ["Divide & Conquer","Backtracking","Pruning","State Space Search","Tail Recursion"],
    difficulty: "Intermediate",
    icon: "Rx",
    order: 8,
  },
  {
    id: "sorting",
    name: "Sorting Algorithms",
    type: "broad",
    description: "Foundational algorithms for ordering data. Compare-based (O(n log n)) vs linear-time (O(n+k)) sorting.",
    when_to_use: "When data needs to be ordered, problems requiring sorted input, or as a subroutine in more complex algorithms.",
    techniques: ["Divide & Conquer","Partitioning","Counting Sort","Heapify"],
    difficulty: "Beginner to Advanced",
    icon: "\\/",
    order: 9,
  },
  {
    id: "greedy",
    name: "Greedy Algorithms",
    type: "broad",
    description: "Make locally optimal choice at each step, hoping it leads to global optimum. Simple when applicable, but correctness must be proven.",
    when_to_use: "Optimization problems with greedy choice property and optimal substructure — scheduling, coin change, Huffman coding.",
    techniques: ["Sorting + Selection","Activity Selection","Fractional Knapsack","Huffman Coding","Job Sequencing"],
    difficulty: "Intermediate",
    icon: "Gx",
    order: 10,
  },
  {
    id: "heaps",
    name: "Heaps & Priority Queues",
    type: "broad",
    description: "Tree-based structure maintaining min/max at root. Essential for priority-based processing and streaming algorithms.",
    when_to_use: "Kth smallest/largest, merge K sorted lists, median in stream, task scheduling, Dijkstra's algorithm.",
    techniques: ["Min-Heap","Max-Heap","Two-Heap (Median)","Heapify","Heap Sort"],
    difficulty: "Intermediate",
    icon: "Hp",
    order: 11,
  },
  {
    id: "bit-manipulation",
    name: "Bit Manipulation",
    type: "broad",
    description: "Operate directly on bits using AND, OR, XOR, shifts. Ultra-fast tricks for space optimization and clever algorithms.",
    when_to_use: "Power-of-2 checks, counting set bits, XOR-based problems (single number), subset generation, fast arithmetic.",
    techniques: ["Bitmask DP","XOR Properties","Kernighan's Algorithm","Bit Hacks","Bit Subsets"],
    difficulty: "Intermediate to Advanced",
    icon: "01",
    order: 12,
  },
  {
    id: "maths",
    name: "Mathematics",
    type: "broad",
    description: "Number theory, combinatorics, probability, and geometry problems. Master GCD/LCM, primality, modulo arithmetic.",
    when_to_use: "Prime numbers, divisors, factorial computations, combinatorics (nCr), modular arithmetic, probability calculations.",
    techniques: ["Sieve of Eratosthenes","GCD/Euclidean","Modular Exponentiation","nCr Combinations","Linear Diophantine"],
    difficulty: "Intermediate",
    icon: "Pi",
    order: 13,
  },
  {
    id: "matrix",
    name: "Matrix / 2D Arrays",
    type: "broad",
    description: "Multi-dimensional array problems: spiral traversal, rotation, search in sorted matrix, and path finding in grids.",
    when_to_use: "Grid-based problems, image processing, 2D search, path finding, matrix transformations.",
    techniques: ["DFS/BFS on Grid","Spiral Traversal","Rotate/Transpose","Binary Search on Matrix","Row-Column Elimination"],
    difficulty: "Intermediate",
    icon: "#",
    order: 14,
  },

  // ========== TECHNIQUE PATTERNS ==========
  {
    id: "two-pointers",
    name: "Two Pointers",
    type: "technique",
    parent: "arrays",
    description: "Use two pointers to traverse data in one pass instead of nested loops. Classic for sorted arrays and linked lists.",
    when_to_use: "Sorted arrays, palindrome checking, removing duplicates, finding pairs that satisfy conditions.",
    techniques: ["Opposite Direction","Same Direction (Fast/Slow)","Collision Pointers"],
    difficulty: "Beginner to Intermediate",
    icon: "<-",
    order: 101,
  },
  {
    id: "sliding-window",
    name: "Sliding Window",
    type: "technique",
    parent: "arrays",
    description: "Maintain a window over array/string that expands/contracts to satisfy constraints. Transform O(n²) into O(n).",
    when_to_use: "Problems asking for subarray/substring with specific properties — max sum, min length, distinct characters.",
    techniques: ["Fixed Window","Variable Window","HashMap + Window","Deque for Max/Min"],
    difficulty: "Intermediate",
    icon: "<->",
    order: 102,
  },
  {
    id: "prefix-sum",
    name: "Prefix Sum",
    type: "technique",
    parent: "arrays",
    description: "Precompute cumulative sums to answer range sum queries in O(1). Essential for subarray sum problems.",
    when_to_use: "Range sum queries, subarray sum equals k, equilibrium index, 2D range sums, difference arrays.",
    techniques: ["1D Prefix Sum","2D Prefix Sum","Difference Array","HashMap + Prefix Sum"],
    difficulty: "Intermediate",
    icon: "∑",
    order: 103,
  },
  {
    id: "kadanes-algorithm",
    name: "Kadane's Algorithm",
    type: "technique",
    parent: "arrays",
    description: "Find maximum subarray sum in O(n) using local/global optimization. Tracks running sum and resets when negative.",
    when_to_use: "Maximum subarray sum, maximum product subarray, maximum sum circular subarray, best time to buy/sell stock.",
    techniques: ["Local Max Tracking","Global Max Update","Circular Kadane","2D Kadane"],
    difficulty: "Intermediate",
    icon: "K",
    order: 104,
  },
  {
    id: "merge-intervals",
    name: "Merge Intervals",
    type: "technique",
    parent: "arrays",
    description: "Sort intervals by start time, then merge overlapping ones. A fundamental pattern for interval-based problems.",
    when_to_use: "Meeting rooms, interval scheduling, insert/merge intervals, interval intersection, free time.",
    techniques: ["Sort by Start","Overlap Detection","Greedy Merge","Sweep Line"],
    difficulty: "Intermediate",
    icon: "==",
    order: 105,
  },
  {
    id: "cyclic-sort",
    name: "Cyclic Sort",
    type: "technique",
    parent: "arrays",
    description: "Place each element at its correct index by swapping. Perfect for problems where numbers are in range [1, n].",
    when_to_use: "Find missing/duplicate numbers in range [1,n], find all duplicates, first missing positive, corrupted pair.",
    techniques: ["Index Swapping","Detection","Range Checking"],
    difficulty: "Intermediate",
    icon: "↻",
    order: 106,
  },
  {
    id: "fast-slow-pointers",
    name: "Fast & Slow Pointers",
    type: "technique",
    parent: "linked-list",
    description: "Use two pointers moving at different speeds. Detect cycles, find middle, and find cycle start in linked structures.",
    when_to_use: "Cycle detection in linked lists, finding middle node, palindrome list, cycle start, happy number.",
    techniques: ["Floyd's Cycle Detection","Middle Finding","Cycle Start Detection"],
    difficulty: "Intermediate",
    icon: "»",
    order: 107,
  },
  {
    id: "inplace-reversal",
    name: "In-place Reversal of Linked List",
    type: "technique",
    parent: "linked-list",
    description: "Reverse parts of a linked list in-place by rewiring pointers. Iterative approach using prev/curr/next pattern.",
    when_to_use: "Reverse linked list, reverse sub-list, reverse in k-groups, palindrome check, rotate list.",
    techniques: ["Three Pointers (Prev/Curr/Next)","Recursive Reversal","K-Group Reversal"],
    difficulty: "Intermediate",
    icon: "⤾",
    order: 108,
  },
  {
    id: "monotonic-stack",
    name: "Monotonic Stack",
    type: "technique",
    parent: "stack-queue",
    description: "Maintain a stack with strictly increasing/decreasing order. Find next/previous greater/smaller elements in O(n).",
    when_to_use: "Next greater element, largest rectangle in histogram, daily temperatures, stock span, trapping rain water.",
    techniques: ["Increasing Stack","Decreasing Stack","Next Greater Element","Previous Smaller Element"],
    difficulty: "Advanced",
    icon: "⊢",
    order: 109,
  },
  {
    id: "tree-bfs",
    name: "Tree BFS (Level Order)",
    type: "technique",
    parent: "trees",
    description: "Traverse a tree level by level using a queue. Essential for problems involving tree levels or shortest paths.",
    when_to_use: "Level order traversal, right side view, zigzag traversal, level averages, connect level nodes.",
    techniques: ["Queue-based BFS","Level-by-Level Processing","Reverse Level Order","Zigzag BFS"],
    difficulty: "Intermediate",
    icon: "⬍",
    order: 110,
  },
  {
    id: "tree-dfs",
    name: "Tree DFS (In/Pre/Post Order)",
    type: "technique",
    parent: "trees",
    description: "Recursive depth-first traversal of trees. Preorder (root-left-right), inorder (left-root-right), postorder (left-right-root).",
    when_to_use: "Path sum, subtree check, tree serialization, BST validation, kth smallest, LCA, diameter, max path sum.",
    techniques: ["Preorder","Inorder","Postorder","Morris Traversal","Iterative Stack DFS"],
    difficulty: "Intermediate",
    icon: "⬇",
    order: 111,
  },
  {
    id: "trie",
    name: "Trie (Prefix Tree)",
    type: "technique",
    parent: "strings",
    description: "A tree-like data structure storing strings character by character. Enables O(L) prefix search and insert.",
    when_to_use: "Word search in dictionary, autocomplete, spell checker, longest prefix matching, word break, IP routing.",
    techniques: ["Array-based Trie","HashMap-based Trie","Trie with Counts","Compressed Trie (Radix)"],
    difficulty: "Advanced",
    icon: "△",
    order: 112,
  },
  {
    id: "topological-sort",
    name: "Topological Sort",
    type: "technique",
    parent: "graphs",
    description: "Linear ordering of DAG vertices where each edge u→v has u before v. Uses Kahn's algorithm or DFS-based approach.",
    when_to_use: "Course schedule, dependency resolution, build order, alien dictionary, task scheduling, cycle detection.",
    techniques: ["Kahn's BFS (Indegree)","DFS with Stack","Cycle Detection"],
    difficulty: "Advanced",
    icon: "⬆",
    order: 113,
  },
  {
    id: "union-find",
    name: "Union-Find (Disjoint Set)",
    type: "technique",
    parent: "graphs",
    description: "Data structure for tracking elements partitioned into disjoint sets. Supports union and find operations near O(1).",
    when_to_use: "Connected components, cycle detection in undirected graph, number of islands, redundant connection, accounts merge.",
    techniques: ["Path Compression","Union by Rank","Union by Size","DSU with Reverse Queries"],
    difficulty: "Advanced",
    icon: "∪",
    order: 114,
  },
  {
    id: "shortest-path",
    name: "Shortest Path Algorithms",
    type: "technique",
    parent: "graphs",
    description: "Find minimum distance paths in weighted graphs. Dijkstra (non-negative), Bellman-Ford (negative allowed), Floyd-Warshall (all pairs).",
    when_to_use: "Navigation, network routing, cheapest flights, minimum time to reach destination, negative cycle detection.",
    techniques: ["Dijkstra (Min-Heap)","Bellman-Ford (Edge Relaxation)","Floyd-Warshall (DP)","0-1 BFS"],
    difficulty: "Advanced",
    icon: "🠖",
    order: 115,
  },
  {
    id: "mst",
    name: "Minimum Spanning Tree",
    type: "technique",
    parent: "graphs",
    description: "Find a subset of edges connecting all vertices with minimum total weight. Prim's (grows tree) vs Kruskal's (sort & union).",
    when_to_use: "Network design (roads, cables), minimum cost to connect points, cluster analysis, approximation algorithms.",
    techniques: ["Prim's Algorithm (Heap)","Kruskal's Algorithm (Union-Find)","Boruvka's Algorithm"],
    difficulty: "Advanced",
    icon: "⊞",
    order: 116,
  },
  {
    id: "binary-search",
    name: "Binary Search",
    type: "technique",
    parent: "arrays",
    categories: ["binary-search", "searching"],
    description: "Divide the search space in half at each step. Works on sorted data and monotonic functions. O(log n) efficiency.",
    when_to_use: "Sorted arrays, searching in rotated arrays, finding peaks, or any monotonic predicate (minimize/maximize problems).",
    techniques: ["Standard BS","Lower/Upper Bound","BS on Answer","Search Rotated","Ternary Search"],
    difficulty: "Intermediate",
    icon: "<>",
    order: 117,
  },
  {
    id: "backtracking",
    name: "Backtracking (Subsets & Permutations)",
    type: "technique",
    parent: "recursion",
    description: "Systematically explore all candidates by building incrementally and abandoning (backtracking) when invalid.",
    when_to_use: "Subsets, permutations, combinations, N-Queens, Sudoku solver, generate parentheses, letter combinations.",
    techniques: ["Inclusion/Exclusion","Swap-Based","Visited Array","Pruning","Constraint Propagation"],
    difficulty: "Advanced",
    icon: "±",
    order: 118,
  },
  {
    id: "knapsack",
    name: "0/1 Knapsack DP",
    type: "technique",
    parent: "dp",
    description: "Classic DP pattern: given items with weights and values, maximize value without exceeding capacity. Each item taken once.",
    when_to_use: "Partition equal subset sum, target sum, last stone weight, subset sum, ones and zeroes, combination sum.",
    techniques: ["2D DP Table","1D Space Optimization","Top-Down Memoization","Subset Sum Pattern"],
    difficulty: "Advanced",
    icon: "🎒",
    order: 119,
  },
  {
    id: "lcs",
    name: "Longest Common Subsequence DP",
    type: "technique",
    parent: "dp",
    description: "Find longest subsequence common to two sequences. DP[i][j] = optimal solution for prefixes of lengths i and j.",
    when_to_use: "Longest common subsequence, edit distance, longest palindromic subsequence (reverse+LCS), string interleaving.",
    techniques: ["2D DP Table","Space Optimized 1D","Recursive + Memo","Printing LCS"],
    difficulty: "Advanced",
    icon: "↔",
    order: 120,
  },
  {
    id: "lis",
    name: "Longest Increasing Subsequence DP",
    type: "technique",
    parent: "dp",
    description: "Find longest subsequence where elements increase. O(n²) DP or O(n log n) with patience sorting (binary search).",
    when_to_use: "Longest increasing subsequence, Russian doll envelopes, maximum chain length, minimum deletions to sort.",
    techniques: ["O(n²) DP","Patience Sorting O(n log n)","Binary Search on Tails","Width Sorting for Envelopes"],
    difficulty: "Advanced",
    icon: "📈",
    order: 121,
  },
  {
    id: "dp-on-grid",
    name: "DP on Grid",
    type: "technique",
    parent: "dp",
    description: "Solve grid-based problems using DP. Move right/down, find paths, min/max path sum, unique paths, obstacles.",
    when_to_use: "Unique paths, minimum path sum, triangle, maximum square, dungeon game, cherry pickup, robot in grid.",
    techniques: ["2D DP Table","1D Space Optimization","Memoization","In-place Modification"],
    difficulty: "Advanced",
    icon: "⊞",
    order: 122,
  },
  {
    id: "moores-algorithm",
    name: "Boyer-Moore Majority Vote",
    type: "technique",
    parent: "arrays",
    description: "Find majority element (> n/2 or > n/3) in O(n) time and O(1) space using cancellation of different elements.",
    when_to_use: "Majority element, majority element II, minimum index with equal frequency, elements appearing more than n/k.",
    techniques: ["Single Candidate","Dual Candidate","Cancellation Phase","Verification Phase"],
    difficulty: "Intermediate",
    icon: "⅔",
    order: 123,
  },
  {
    id: "maths-technique",
    name: "Number Theory & Combinatorics",
    type: "technique",
    parent: "maths",
    description: "GCD/LCM, prime sieves, modular arithmetic, combinatorics (nCr), fast exponentiation, and factorization.",
    when_to_use: "Prime checking, GCD problems, combinatorial counting, modulo exponentiation, factorial trailing zeros.",
    techniques: ["Sieve of Eratosthenes","Euclidean GCD","Modular Exponentiation","nCr mod p","Pollard Rho"],
    difficulty: "Intermediate to Advanced",
    icon: "π",
    order: 124,
  },
  {
    id: "bit-manipulation-technique",
    name: "Bit Manipulation Tricks",
    type: "technique",
    parent: "bit-manipulation",
    description: "XOR properties, bit counting, masking, and clever bit-level operations for space/time efficient solutions.",
    when_to_use: "Find unique element (XOR), power of 2, count set bits, subset generation, swap without temp, reverse bits.",
    techniques: ["XOR Properties","Kernighan's Bit Counting","Bitmask Subsets","Bit Hacks (n & n-1)"],
    difficulty: "Intermediate",
    icon: "01",
    order: 125,
  },
  {
    id: "segment-tree",
    name: "Segment Tree & Fenwick Tree",
    type: "technique",
    parent: "arrays",
    description: "Tree-based structures for range queries (sum, min, max) and point/range updates in O(log n).",
    when_to_use: "Range sum queries with updates, range minimum query, count inversions, range XOR, 2D range queries.",
    techniques: ["Segment Tree (Recursive/Iterative)","Fenwick (Binary Indexed Tree)","Lazy Propagation","2D Fenwick"],
    difficulty: "Advanced",
    icon: "△",
    order: 126,
  },
  {
    id: "binary-search-tree",
    name: "Binary Search Tree Properties",
    type: "technique",
    parent: "trees",
    description: "BST property: left < root < right. Inorder traversal gives sorted order. Search, insert, delete in O(log n) average.",
    when_to_use: "Validate BST, kth smallest/largest, inorder successor/predecessor, range sum BST, convert sorted array to BST.",
    techniques: ["Inorder Traversal","Recursive Validation with Bounds","Floor/Ceiling","Morris Traversal"],
    difficulty: "Intermediate",
    icon: "🌲",
    order: 127,
  },

  // ========== NEW TECHNIQUE PATTERNS ==========
  {
    id: "divide-conquer",
    name: "Divide & Conquer",
    type: "technique",
    parent: "recursion",
    description: "Split problem into independent subproblems, solve recursively, combine results. Foundation of merge sort, quick sort, and many algorithms.",
    when_to_use: "Problems where solutions combine results from independent halves: sorting, maximum subarray, closest pair, binary tree construction, exponentiation.",
    techniques: ["Merge Sort","Quick Sort","Binary Search","Strassen's Matrix","Closest Pair","Karatsuba"],
    difficulty: "Intermediate to Advanced",
    icon: "⊘",
    order: 128,
  },
  {
    id: "sweep-line",
    name: "Sweep Line Algorithm",
    type: "technique",
    parent: "arrays",
    description: "Process events in sorted order, maintaining a running state. Transform interval/range problems into sequential events.",
    when_to_use: "Interval intersections, meeting rooms, skyline problem, range overlap, employee free time, interval covering, count of intervals covering points.",
    techniques: ["Event Sorting","Active Interval Tracking","Line Sweep","Difference Array","Interval Tree"],
    difficulty: "Advanced",
    icon: "⇌",
    order: 129,
  },
  {
    id: "rolling-hash",
    name: "Rolling Hash / Rabin-Karp",
    type: "technique",
    parent: "strings",
    description: "Hash a sliding window of characters using a rolling polynomial hash. Compare substrings in O(1) after O(n) preprocessing.",
    when_to_use: "Pattern matching, longest common substring, repeated substring, palindrome detection, plagiarism detection, string hashing.",
    techniques: ["Polynomial Rolling Hash","Double Hashing","Rabin-Karp","Binary Search + Hash","Z-Algorithm"],
    difficulty: "Advanced",
    icon: "#",
    order: 130,
  },
  {
    id: "reservoir-sampling",
    name: "Reservoir Sampling",
    type: "technique",
    parent: "maths",
    description: "Select k random elements from a stream of unknown size in O(n) with O(k) space. Each element has equal probability of selection.",
    when_to_use: "Random sampling from data streams, random node from linked list, random pick with weight, shuffling algorithms, online selection.",
    techniques: ["Simple Reservoir (k=1)","General Reservoir (k>1)","Weighted Reservoir","Stream Sampling"],
    difficulty: "Advanced",
    icon: "⌲",
    order: 131,
  },
  {
    id: "design-ds",
    name: "Data Structure Design",
    type: "technique",
    parent: "linked-list",
    description: "Design custom data structures combining multiple primitives (arrays, hashmaps, linked lists) for specific operation requirements.",
    when_to_use: "LRU/LFU Cache, Insert-Delete-GetRandom, Stream median, time-based key-value store, all O(1) data structures, prefix-suffix search.",
    techniques: ["LRU Cache","LFU Cache","HashMap + Doubly Linked List","Insert-Delete-Random","Two-Layer Maps"],
    difficulty: "Advanced",
    icon: "⚙",
    order: 132,
  },
];
