export default [
  {
    id: "arrays",
    name: "Arrays",
    description: "Problems involving contiguous memory blocks. Master indexing, traversal, subarray manipulation, and in-place operations.",
    when_to_use: "When order matters, you need fast index access, or the problem involves contiguous sequences of elements.",
    techniques: ["Two-pointer","Sliding Window","Prefix Sum","Kadane's Algorithm","Dutch National Flag"],
    difficulty: "Beginner to Advanced",
    icon: "[]",
    order: 1,
  },
  {
    id: "strings",
    name: "Strings",
    description: "Text processing problems: matching, rotation, palindrome checking, substring search, and character frequency analysis.",
    when_to_use: "When dealing with text, character sequences, or pattern matching within words.",
    techniques: ["Two-pointer","Sliding Window","Rabin-Karp","KMP","Trie","Frequency Map"],
    difficulty: "Beginner to Advanced",
    icon: "Aa",
    order: 2,
  },
  {
    id: "sliding-window",
    name: "Sliding Window",
    description: "Maintain a window over array/string that expands/contracts to satisfy constraints. Transform O(n²) brute-force into O(n).",
    when_to_use: "Problems asking for subarray/substring with specific properties — max sum, min length, distinct characters, target sum.",
    techniques: ["Fixed Window","Variable Window","HashMap + Window","Deque for Max/Min"],
    difficulty: "Intermediate",
    icon: "<->",
    order: 3,
  },
  {
    id: "two-pointers",
    name: "Two Pointers",
    description: "Use two pointers to traverse data in one pass instead of nested loops. Classic for sorted arrays and linked lists.",
    when_to_use: "Sorted arrays, palindrome checking, removing duplicates, finding pairs that satisfy conditions.",
    techniques: ["Opposite Direction","Same Direction (Fast/Slow)","Sliding Window variant","Collision Pointers"],
    difficulty: "Beginner to Intermediate",
    icon: "<-",
    order: 4,
  },
  {
    id: "linked-list",
    name: "Linked Lists",
    description: "Node-based sequential structure. Master pointer manipulation, reversal, cycle detection, and merging.",
    when_to_use: "When frequent insertions/deletions are needed, size may grow dynamically, or circular/cyclic structures.",
    techniques: ["Slow-Fast Pointer","Dummy Node","Recursive Reversal","Runner Technique"],
    difficulty: "Intermediate",
    icon: "->",
    order: 5,
  },
  {
    id: "stacks-queues",
    name: "Stacks & Queues",
    description: "LIFO/FIFO structures essential for expression evaluation, monotonic patterns, BFS/DFS, and undo operations.",
    when_to_use: "When order of processing depends on nesting (stack) or level-order (queue), nearest greater/smaller elements.",
    techniques: ["Monotonic Stack","Deque","Two Queues/Stacks","Circular Buffer"],
    difficulty: "Intermediate",
    icon: "||",
    order: 6,
  },
  {
    id: "sorting",
    name: "Sorting Algorithms",
    description: "Foundational algorithms for ordering data. Compare-based (O(n log n)) vs linear-time (O(n+k)) sorting.",
    when_to_use: "When data needs to be ordered, problems requiring sorted input, or as a subroutine in more complex algorithms.",
    techniques: ["Divide & Conquer","Partitioning","Counting Sort","Heapify"],
    difficulty: "Beginner to Advanced",
    icon: "\\/",
    order: 7,
  },
  {
    id: "binary-search",
    name: "Binary Search",
    description: "Divide the search space in half at each step. Works on sorted data and monotonic functions. O(log n) efficiency.",
    when_to_use: "Sorted arrays, searching in rotated arrays, finding peaks, or any monotonic predicate (minimize/maximize problems).",
    techniques: ["Standard BS","Lower/Upper Bound","BS on Answer","Search Rotated","Ternary Search"],
    difficulty: "Intermediate",
    icon: "<>",
    order: 8,
  },
  {
    id: "trees",
    name: "Trees",
    description: "Hierarchical data structures. Master traversals (inorder/preorder/postorder/level-order), BSTs, and recursion.",
    when_to_use: "Hierarchical data, binary search trees, expression trees, decision trees, or any parent-child relationship.",
    techniques: ["Recursive DFS","Iterative DFS (Stack)","BFS / Level Order","Morris Traversal","LCA"],
    difficulty: "Intermediate to Advanced",
    icon: "^Y",
    order: 9,
  },
  {
    id: "graphs",
    name: "Graphs",
    description: "Nodes connected by edges. Model networks, relationships, paths, and dependencies with traversal and shortest-path algorithms.",
    when_to_use: "Networks, paths, connectivity, dependency resolution, shortest path, cycles, or topological ordering.",
    techniques: ["DFS","BFS","Dijkstra","Union-Find","Topological Sort","Floyd-Warshall","Bellman-Ford"],
    difficulty: "Advanced",
    icon: "/\\",
    order: 10,
  }
]
