export default [
  {
    id: "arrays",
    name: "Arrays",
    description: "Problems involving contiguous memory blocks. Master indexing, traversal, subarray manipulation, and in-place operations.",
    when_to_use: "When order matters, you need fast index access, or the problem involves contiguous sequences of elements.",
    techniques: ["Two-pointer","Sliding Window","Prefix Sum","Kadane's Algorithm","Dutch National Flag"],
    difficulty: "Beginner to Advanced",
    icon: "[]",
    order: 1,
  },
  {
    id: "strings",
    name: "Strings",
    description: "Text processing problems: matching, rotation, palindrome checking, substring search, and character frequency analysis.",
    when_to_use: "When dealing with text, character sequences, or pattern matching within words.",
    techniques: ["Two-pointer","Sliding Window","Rabin-Karp","KMP","Trie","Frequency Map"],
    difficulty: "Beginner to Advanced",
    icon: "Aa",
    order: 2,
  },
  {
    id: "sliding-window",
    name: "Sliding Window",
    description: "Maintain a window over array/string that expands/contracts to satisfy constraints. Transform O(n²) brute-force into O(n).",
    when_to_use: "Problems asking for subarray/substring with specific properties — max sum, min length, distinct characters, target sum.",
    techniques: ["Fixed Window","Variable Window","HashMap + Window","Deque for Max/Min"],
    difficulty: "Intermediate",
    icon: "<->",
    order: 3,
  },
  {
    id: "two-pointers",
    name: "Two Pointers",
    description: "Use two pointers to traverse data in one pass instead of nested loops. Classic for sorted arrays and linked lists.",
    when_to_use: "Sorted arrays, palindrome checking, removing duplicates, finding pairs that satisfy conditions.",
    techniques: ["Opposite Direction","Same Direction (Fast/Slow)","Sliding Window variant","Collision Pointers"],
    difficulty: "Beginner to Intermediate",
    icon: "<-",
    order: 4,
  },
  {
    id: "linked-list",
    name: "Linked Lists",
    description: "Node-based sequential structure. Master pointer manipulation, reversal, cycle detection, and merging.",
    when_to_use: "When frequent insertions/deletions are needed, size may grow dynamically, or circular/cyclic structures.",
    techniques: ["Slow-Fast Pointer","Dummy Node","Recursive Reversal","Runner Technique"],
    difficulty: "Intermediate",
    icon: "->",
    order: 5,
  },
  {
    id: "stacks-queues",
    name: "Stacks & Queues",
    description: "LIFO/FIFO structures essential for expression evaluation, monotonic patterns, BFS/DFS, and undo operations.",
    when_to_use: "When order of processing depends on nesting (stack) or level-order (queue), nearest greater/smaller elements.",
    techniques: ["Monotonic Stack","Deque","Two Queues/Stacks","Circular Buffer"],
    difficulty: "Intermediate",
    icon: "||",
    order: 6,
  }
]
