const linkedListLessons = [
  {
    id: 'lesson-42',
    title: 'Singly Linked List',
    category: 'linked-list',
    order_index: 42,
    content: '## What is a Linked List?\n\nA linked list is a linear data structure where elements (nodes) are connected via pointers. Unlike arrays, linked lists do not store elements in contiguous memory.\n\n## Node Structure\n\n```cpp\nstruct Node {\n    int data;\n    Node* next;  // Pointer to the next node\n\n    Node(int val) : data(val), next(nullptr) {}\n};\n```\n\n## Basic Operations\n\n### Traversal\n\n```cpp\nvoid printList(Node* head) {\n    Node* current = head;\n    while (current != nullptr) {\n        cout << current->data << \" \";\n        current = current->next;\n    }\n}\n```\n\n### Insertion at Beginning\n\n```cpp\nvoid insertFront(Node*& head, int val) {\n    Node* newNode = new Node(val);\n    newNode->next = head;\n    head = newNode;\n}\n```\n\n### Insertion at End\n\n```cpp\nvoid insertEnd(Node*& head, int val) {\n    Node* newNode = new Node(val);\n    if (head == nullptr) { head = newNode; return; }\n\n    Node* last = head;\n    while (last->next != nullptr) last = last->next;\n    last->next = newNode;\n}\n```\n\n### Deletion\n\n```cpp\nvoid deleteNode(Node*& head, int val) {\n    if (head == nullptr) return;\n\n    if (head->data == val) {\n        Node* temp = head;\n        head = head->next;\n        delete temp;\n        return;\n    }\n\n    Node* current = head;\n    while (current->next != nullptr && current->next->data != val)\n        current = current->next;\n\n    if (current->next != nullptr) {\n        Node* temp = current->next;\n        current->next = temp->next;\n        delete temp;\n    }\n}\n```\n\n### Search\n\n```cpp\nbool search(Node* head, int val) {\n    while (head != nullptr) {\n        if (head->data == val) return true;\n        head = head->next;\n    }\n    return false;\n}\n```\n\n## Complexity\n\n| Operation | Time |\n|-----------|------|\n| Access by index | O(n) |\n| Insert at beginning | O(1) |\n| Insert at end | O(n) |\n| Delete by value | O(n) |\n| Search | O(n) |\n\n## Linked List vs Array\n\n| Aspect | Linked List | Array |\n|--------|------------|-------|\n| Memory | Non-contiguous, dynamic | Contiguous, fixed |\n| Access | O(n) | O(1) |\n| Insert/delete at start | O(1) | O(n) |\n| Extra memory per element | Pointer overhead | None |\n\n## Best Practices\n\n1. Always check for `nullptr` before dereferencing\n2. Use a head pointer passed by reference for modifications\n3. Draw pictures when implementing pointer changes\n4. Handle edge cases: empty list, single node\n5. Consider using a dummy/sentinel node to simplify operations',
    code_example: '#include <iostream>\nusing namespace std;\n\nstruct Node {\n    int data;\n    Node* next;\n    Node(int val) : data(val), next(nullptr) {}\n};\n\nvoid printList(Node* head) {\n    while (head) { cout << head->data << \" \"; head = head->next; }\n    cout << endl;\n}\n\nvoid insertFront(Node*& head, int val) {\n    Node* n = new Node(val);\n    n->next = head;\n    head = n;\n}\n\nvoid insertEnd(Node*& head, int val) {\n    Node* n = new Node(val);\n    if (!head) { head = n; return; }\n    Node* last = head;\n    while (last->next) last = last->next;\n    last->next = n;\n}\n\nvoid deleteByValue(Node*& head, int val) {\n    if (!head) return;\n    if (head->data == val) { Node* t = head; head = head->next; delete t; return; }\n    Node* cur = head;\n    while (cur->next && cur->next->data != val) cur = cur->next;\n    if (cur->next) { Node* t = cur->next; cur->next = t->next; delete t; }\n}\n\nint main() {\n    Node* head = nullptr;\n    insertEnd(head, 10);\n    insertFront(head, 5);\n    insertEnd(head, 20);\n    insertFront(head, 1);\n    cout << \"List: \"; printList(head);\n    deleteByValue(head, 10);\n    cout << \"After delete 10: \"; printList(head);\n    return 0;\n}'
  },
  {
    id: 'lesson-43',
    title: 'Doubly Linked List',
    category: 'linked-list',
    order_index: 43,
    content: '## Doubly Linked List\n\nEach node has pointers to BOTH the next and previous nodes. This enables traversal in both directions and O(1) deletion given a node pointer.\n\n## Node Structure\n\n```cpp\nstruct Node {\n    int data;\n    Node* prev;\n    Node* next;\n\n    Node(int val) : data(val), prev(nullptr), next(nullptr) {}\n};\n```\n\n## Key Operations\n\n### Insert at Front\n\n```cpp\nvoid insertFront(Node*& head, int val) {\n    Node* newNode = new Node(val);\n    newNode->next = head;\n    if (head != nullptr) head->prev = newNode;\n    head = newNode;\n}\n```\n\n### Insert at End\n\n```cpp\nvoid insertEnd(Node*& head, int val) {\n    Node* newNode = new Node(val);\n    if (head == nullptr) { head = newNode; return; }\n\n    Node* last = head;\n    while (last->next != nullptr) last = last->next;\n    last->next = newNode;\n    newNode->prev = last;\n}\n```\n\n### Delete a Node\n\n```cpp\nvoid deleteNode(Node*& head, Node* del) {\n    if (head == nullptr || del == nullptr) return;\n\n    if (head == del) head = del->next;\n\n    if (del->next != nullptr) del->next->prev = del->prev;\n    if (del->prev != nullptr) del->prev->next = del->next;\n\n    delete del;\n}\n```\n\n### Reverse Traversal\n\n```cpp\nvoid printReverse(Node* head) {\n    if (head == nullptr) return;\n    while (head->next != nullptr) head = head->next;\n\n    while (head != nullptr) {\n        cout << head->data << \" \";\n        head = head->prev;\n    }\n}\n```\n\n## Singly vs Doubly Linked List\n\n| Aspect | Singly | Doubly |\n|--------|--------|--------|\n| Memory per node | 1 pointer | 2 pointers |\n| Traversal | Forward only | Both directions |\n| Delete given node* | O(n) | O(1) |\n| Implementation complexity | Simple | Moderate |\n\n## std::list\n\nC++ STL provides `std::list` — a doubly linked list with full iterator support:\n\n```cpp\nlist<int> lst = {1, 2, 3};\nlst.push_back(4);\nlst.push_front(0);\nlst.pop_front();\nlst.pop_back();\nlst.insert(lst.begin(), 10);\nlst.erase(--lst.end());\nlst.reverse();\nlst.sort();\n```\n\n## Best Practices\n\n1. Always update BOTH prev and next pointers\n2. Check for nullptr before dereferencing both directions\n3. Delete nodes in reverse order of creation\n4. Use `std::list` unless you need custom low-level control',
    code_example: '#include <iostream>\nusing namespace std;\n\nstruct Node {\n    int data;\n    Node* prev;\n    Node* next;\n    Node(int val) : data(val), prev(nullptr), next(nullptr) {}\n};\n\nvoid insertEnd(Node*& head, int val) {\n    Node* n = new Node(val);\n    if (!head) { head = n; return; }\n    Node* last = head;\n    while (last->next) last = last->next;\n    last->next = n;\n    n->prev = last;\n}\n\nvoid printForward(Node* head) {\n    while (head) { cout << head->data << \" \"; head = head->next; }\n    cout << endl;\n}\n\nvoid printBackward(Node* head) {\n    if (!head) return;\n    while (head->next) head = head->next;\n    while (head) { cout << head->data << \" \"; head = head->prev; }\n    cout << endl;\n}\n\nint main() {\n    Node* head = nullptr;\n    for (int i = 1; i <= 5; i++) insertEnd(head, i);\n    cout << \"Forward:  \"; printForward(head);\n    cout << \"Backward: \"; printBackward(head);\n    return 0;\n}'
  },
  {
    id: 'lesson-44',
    title: 'Circular Linked List',
    category: 'linked-list',
    order_index: 44,
    content: '## Circular Linked List\n\nIn a circular linked list, the last node points back to the first (or head) instead of nullptr. This creates a circular structure with no natural beginning or end.\n\n## Circular Singly Linked List\n\n```cpp\nstruct Node {\n    int data;\n    Node* next;\n    Node(int val) : data(val), next(nullptr) {}\n};\n```\n\nThe last node\'s next points to head (not nullptr).\n\n### Traversal\n\nMust detect when we\'ve returned to the start:\n\n```cpp\nvoid printCircular(Node* head) {\n    if (head == nullptr) return;\n    Node* current = head;\n    do {\n        cout << current->data << \" \";\n        current = current->next;\n    } while (current != head);\n    cout << endl;\n}\n```\n\nUse `do-while` to ensure we visit at least the head node.\n\n### Insert at End\n\n```cpp\nvoid insertEnd(Node*& head, int val) {\n    Node* newNode = new Node(val);\n    if (head == nullptr) {\n        head = newNode;\n        newNode->next = head;  // Point to itself\n        return;\n    }\n\n    Node* last = head;\n    while (last->next != head) last = last->next;\n    last->next = newNode;\n    newNode->next = head;\n}\n```\n\n## Circular Doubly Linked List\n\nLast node\'s next points to head, head\'s prev points to last:\n\n```cpp\nstruct Node {\n    int data;\n    Node* prev;\n    Node* next;\n    Node(int val) : data(val), prev(nullptr), next(nullptr) {}\n};\n\nvoid insertEnd(Node*& head, int val) {\n    Node* newNode = new Node(val);\n    if (!head) {\n        head = newNode;\n        head->next = head;\n        head->prev = head;\n        return;\n    }\n    Node* last = head->prev;\n    last->next = newNode;\n    newNode->prev = last;\n    newNode->next = head;\n    head->prev = newNode;\n}\n```\n\n## Applications\n\n1. **Round-robin scheduling**: OS process scheduling\n2. **Music playlist**: Repeat one / repeat all\n3. **Multiplayer games**: Turn-based games cycling through players\n4. **Memory management**: Slab allocators, buddy systems\n\n## Josephus Problem\n\nClassic circular linked list problem: N people in a circle, eliminate every k-th person. Find the last survivor.\n\n```cpp\nint josephus(int n, int k) {\n    // Build circular list of 1..n\n    // Eliminate every k-th node until one remains\n}\n```\n\n## Advantages over Linear Lists\n\n1. No need to maintain a tail pointer for O(1) access to end\n2. Can traverse the entire list from any starting point\n3. Natural for cyclic/round-robin applications\n\n## Best Practices\n\n1. Always maintain the circular invariant (last->next = head)\n2. Use do-while for traversal to avoid skipping head\n3. Check for the self-loop case (single node)\n4. Be careful with infinite loops in traversal\n\n## Complexity\n\nSame as singly/doubly linked list for all operations, but traversal termination detection requires checking against the head rather than nullptr.',
    code_example: '#include <iostream>\nusing namespace std;\n\nstruct Node {\n    int data;\n    Node* next;\n    Node(int val) : data(val), next(nullptr) {}\n};\n\nvoid insertEnd(Node*& head, int val) {\n    Node* n = new Node(val);\n    if (!head) { head = n; head->next = head; return; }\n    Node* last = head;\n    while (last->next != head) last = last->next;\n    last->next = n;\n    n->next = head;\n}\n\nvoid printList(Node* head) {\n    if (!head) return;\n    Node* cur = head;\n    do { cout << cur->data << \" \"; cur = cur->next; } while (cur != head);\n    cout << endl;\n}\n\nvoid deleteHead(Node*& head) {\n    if (!head) return;\n    if (head->next == head) { delete head; head = nullptr; return; }\n    Node* last = head;\n    while (last->next != head) last = last->next;\n    Node* temp = head;\n    head = head->next;\n    last->next = head;\n    delete temp;\n}\n\nint main() {\n    Node* head = nullptr;\n    for (int i = 1; i <= 5; i++) insertEnd(head, i);\n    cout << \"Circular: \"; printList(head);\n    deleteHead(head);\n    cout << \"After delete head: \"; printList(head);\n    return 0;\n}'
  },
  {
    id: 'lesson-45',
    title: 'Linked List Algorithms',
    category: 'linked-list',
    order_index: 45,
    content: '## Essential Linked List Algorithms\n\nThese algorithms are fundamental and frequently appear in coding interviews.\n\n## 1. Reverse a Linked List\n\nIterative approach (three pointers):\n\n```cpp\nNode* reverse(Node* head) {\n    Node* prev = nullptr;\n    Node* current = head;\n    Node* next = nullptr;\n\n    while (current != nullptr) {\n        next = current->next;   // Save next\n        current->next = prev;   // Reverse pointer\n        prev = current;         // Move prev forward\n        current = next;         // Move current forward\n    }\n    return prev;  // New head\n}\n```\n\nRecursive approach:\n\n```cpp\nNode* reverse(Node* head) {\n    if (head == nullptr || head->next == nullptr) return head;\n    Node* rest = reverse(head->next);\n    head->next->next = head;\n    head->next = nullptr;\n    return rest;\n}\n```\n\n## 2. Floyd\'s Cycle Detection (Tortoise and Hare)\n\nDetect if a linked list has a cycle:\n\n```cpp\nbool hasCycle(Node* head) {\n    Node* slow = head;\n    Node* fast = head;\n\n    while (fast != nullptr && fast->next != nullptr) {\n        slow = slow->next;       // Move one step\n        fast = fast->next->next; // Move two steps\n        if (slow == fast) return true;  // Cycle found!\n    }\n    return false;\n}\n```\n\nTo find the START of the cycle:\n1. Detect cycle (slow/fast meet)\n2. Reset slow to head\n3. Move both one step until they meet — that\'s the cycle start\n\n## 3. Find Middle of Linked List\n\n```cpp\nNode* findMiddle(Node* head) {\n    Node* slow = head;\n    Node* fast = head;\n    while (fast != nullptr && fast->next != nullptr) {\n        slow = slow->next;\n        fast = fast->next->next;\n    }\n    return slow;  // Middle node\n}\n```\n\n## 4. Merge Two Sorted Lists\n\n```cpp\nNode* mergeSorted(Node* a, Node* b) {\n    if (!a) return b;\n    if (!b) return a;\n\n    if (a->data <= b->data) {\n        a->next = mergeSorted(a->next, b);\n        return a;\n    } else {\n        b->next = mergeSorted(a, b->next);\n        return b;\n    }\n}\n```\n\n## 5. Remove Nth Node from End\n\nTwo-pointer approach:\n\n```cpp\nNode* removeNthFromEnd(Node* head, int n) {\n    Node* dummy = new Node(0);\n    dummy->next = head;\n    Node* first = dummy;\n    Node* second = dummy;\n\n    for (int i = 0; i <= n; i++) first = first->next;\n    while (first != nullptr) {\n        first = first->next;\n        second = second->next;\n    }\n    Node* temp = second->next;\n    second->next = second->next->next;\n    delete temp;\n    return dummy->next;\n}\n```\n\n## 6. Palindrome Check\n\n1. Find middle\n2. Reverse second half\n3. Compare both halves\n4. Restore the list\n\n## Best Practices\n\n1. Draw the list before coding pointer changes\n2. Use dummy/sentinel nodes to simplify edge cases\n3. Always draw the "before" and "after" of pointer operations\n4. Handle null, single node, and two-node cases separately',
    code_example: '#include <iostream>\nusing namespace std;\n\nstruct Node {\n    int data;\n    Node* next;\n    Node(int val) : data(val), next(nullptr) {}\n};\n\nvoid insertEnd(Node*& head, int val) {\n    Node* n = new Node(val);\n    if (!head) { head = n; return; }\n    Node* last = head;\n    while (last->next) last = last->next;\n    last->next = n;\n}\n\nvoid printList(Node* head) {\n    while (head) { cout << head->data << \" \"; head = head->next; }\n    cout << endl;\n}\n\nNode* reverse(Node* head) {\n    Node* prev = nullptr, *cur = head, *next = nullptr;\n    while (cur) {\n        next = cur->next;\n        cur->next = prev;\n        prev = cur;\n        cur = next;\n    }\n    return prev;\n}\n\nNode* findMiddle(Node* head) {\n    Node *slow = head, *fast = head;\n    while (fast && fast->next) {\n        slow = slow->next;\n        fast = fast->next->next;\n    }\n    return slow;\n}\n\nint main() {\n    Node* head = nullptr;\n    for (int i = 1; i <= 6; i++) insertEnd(head, i);\n    cout << \"Original: \"; printList(head);\n    cout << \"Middle: \" << findMiddle(head)->data << endl;\n    Node* rev = reverse(head);\n    cout << \"Reversed: \"; printList(rev);\n    return 0;\n}'
  }
];
export default linkedListLessons;
