const oopLessons = [
  {
    id: 'lesson-25',
    title: 'Classes & Objects',
    category: 'oop',
    order_index: 25,
    content: '## What is a Class?\n\nA class is a blueprint for creating objects. It encapsulates data (member variables) and behavior (member functions) into a single unit. C++ is an object-oriented language, and classes are the foundation of OOP.\n\n## Defining a Class\n\n```cpp\nclass Dog {\npublic:\n    string name;\n    int age;\n\n    void bark() {\n        cout << "Woof!" << endl;\n    }\n};\n```\n\n## Creating Objects\n\n```cpp\nDog myDog;          // Stack allocation\nmyDog.name = "Buddy";\nmyDog.age = 3;\nmyDog.bark();       // "Woof!"\n\nDog* ptr = new Dog(); // Heap allocation\nptr->name = "Max";\ndelete ptr;\n```\n\n## Access Specifiers\n\n| Specifier | Access |\n|-----------|--------|\n| `public` | Anywhere |\n| `private` | Only within the class |\n| `protected` | Class + derived classes |\n\nBy default, everything in a class is `private`. Use `struct` for all-public by default.\n\n## Member Functions\n\nCan be defined inside (inline) or outside the class:\n```cpp\nclass Rectangle {\n    double width, height;\npublic:\n    double area();  // Declaration only\n};\n\ndouble Rectangle::area() {  // Outside definition\n    return width * height;\n}\n```\n\n## The `this` Pointer\n\nEvery member function has access to `this` — a pointer to the calling object:\n```cpp\nclass Person {\n    string name;\npublic:\n    void setName(string name) {\n        this->name = name;  // Distinguish parameter from member\n    }\n};\n```\n\n## Class vs Struct\n\n- `class`: members are `private` by default\n- `struct`: members are `public` by default\n\nOtherwise, they are identical in C++.\n\n## Best Practices\n1. Make member variables `private`\n2. Provide `public` getters/setters\n3. Keep classes focused (Single Responsibility Principle)\n4. Use initializer lists in constructors\n5. Prefer stack allocation over heap when possible',
    code_example: '#include <iostream>\n#include <string>\nusing namespace std;\n\nclass BankAccount {\nprivate:\n    string owner;\n    double balance;\npublic:\n    BankAccount(string o, double b) : owner(o), balance(b) {}\n\n    void deposit(double amt) {\n        if (amt > 0) balance += amt;\n    }\n\n    bool withdraw(double amt) {\n        if (amt > 0 && amt <= balance) {\n            balance -= amt;\n            return true;\n        }\n        return false;\n    }\n\n    double getBalance() const { return balance; }\n    string getOwner() const { return owner; }\n};\n\nint main() {\n    BankAccount acc("Alice", 1000);\n    acc.deposit(500);\n    acc.withdraw(200);\n    cout << acc.getOwner() << " balance: $" << acc.getBalance() << endl;\n    return 0;\n}'
  },
  {
    id: 'lesson-26',
    title: 'Constructors & Destructors',
    category: 'oop',
    order_index: 26,
    content: '## Constructors\n\nA constructor is a special member function called automatically when an object is created. It has the same name as the class and no return type.\n\n## Default Constructor\n\n```cpp\nclass Point {\n    int x, y;\npublic:\n    Point() { x = 0; y = 0; }  // Default constructor\n};\n\nPoint p;  // Calls default constructor\n```\n\nIf no constructor is defined, the compiler generates a default one. But if you define ANY constructor, the compiler-generated default is NOT created.\n\n## Parameterized Constructor\n\n```cpp\nclass Point {\n    int x, y;\npublic:\n    Point(int a, int b) : x(a), y(b) {}  // Initializer list\n};\n\nPoint p(3, 5);\nPoint q = Point(3, 5);  // Same thing\n```\n\n## Initializer Lists\n\nAlways prefer initializer lists over assignment in constructors:\n```cpp\nclass Student {\n    string name;\n    const int id;       // MUST use initializer list\n    int& ref;           // MUST use initializer list\npublic:\n    Student(string n, int i, int& r) : name(n), id(i), ref(r) {}\n};\n```\n\nReasons: const and reference members REQUIRE initialization, and initializer lists are more efficient (no default construction + assignment).\n\n## Copy Constructor\n\nCreates a new object as a copy of an existing one:\n```cpp\nclass Point {\n    int x, y;\npublic:\n    Point(const Point& other) : x(other.x), y(other.y) {\n        cout << "Copy constructor called" << endl;\n    }\n};\n\nPoint p1(3, 5);\nPoint p2(p1);       // Copy constructor\nPoint p3 = p1;      // Also copy constructor!\n```\n\n## The Rule of Three\n\nIf you need a custom destructor, copy constructor, or copy assignment operator, you likely need all three:\n\n```cpp\nclass StringArray {\n    char** data;\n    int size;\npublic:\n    StringArray(int n) : size(n), data(new char*[n]) {}\n    ~StringArray() { /* cleanup */ }\n    StringArray(const StringArray& other) { /* deep copy */ }\n    StringArray& operator=(const StringArray& other) { /* deep copy */ return *this; }\n};\n```\n\n## Destructors\n\nCalled when an object is destroyed. Use for cleanup (closing files, freeing memory):\n```cpp\nclass Resource {\n    int* data;\npublic:\n    Resource() { data = new int[1000]; }\n    ~Resource() { delete[] data; }\n};\n```\n\n## Virtual Destructors\n\nIf a class has virtual functions, its destructor MUST be virtual:\n```cpp\nclass Base {\npublic:\n    virtual ~Base() {}\n};\n```\n\n## Move Constructors (C++11)\n\nTransfer ownership instead of copying:\n```cpp\nclass Buffer {\n    int* data;\npublic:\n    Buffer(Buffer&& other) noexcept : data(other.data) {\n        other.data = nullptr;  // Steal resource\n    }\n};\n```\n\n## Best Practices\n1. Prefer initializer lists\n2. Mark single-argument constructors `explicit` to prevent implicit conversions\n3. Follow Rule of Three/Five if managing resources\n4. Make destructors virtual in base classes',
    code_example: '#include <iostream>\n#include <cstring>\nusing namespace std;\n\nclass String {\n    char* str;\npublic:\n    String(const char* s) {\n        str = new char[strlen(s) + 1];\n        strcpy(str, s);\n        cout << "Constructed: " << str << endl;\n    }\n\n    ~String() {\n        cout << "Destructed: " << str << endl;\n        delete[] str;\n    }\n\n    String(const String& other) {\n        str = new char[strlen(other.str) + 1];\n        strcpy(str, other.str);\n        cout << "Copied: " << str << endl;\n    }\n\n    void print() const { cout << str << endl; }\n};\n\nint main() {\n    String s1("Hello");\n    String s2 = s1;\n    s1.print();\n    s2.print();\n    return 0;\n}'
  },
  {
    id: 'lesson-27',
    title: 'Inheritance',
    category: 'oop',
    order_index: 27,
    content: '## What is Inheritance?\n\nInheritance lets a class (derived/child) inherit properties and behavior from another class (base/parent). It promotes code reuse and establishes an "is-a" relationship.\n\n## Basic Syntax\n\n```cpp\nclass Base {\n    // ...\n};\n\nclass Derived : access_specifier Base {\n    // ...\n};\n```\n\n## Example\n\n```cpp\nclass Animal {\npublic:\n    void eat() { cout << "Eating" << endl; }\n};\n\nclass Dog : public Animal {\npublic:\n    void bark() { cout << "Woof" << endl; }\n};\n\nDog d;\nd.eat();   // Inherited from Animal\nd.bark();  // Own method\n```\n\n## Access Specifiers in Inheritance\n\n| Base member | public inheritance | protected inheritance | private inheritance |\n|------------|-------------------|---------------------|-------------------|\n| public | public | protected | private |\n| protected | protected | protected | private |\n| private | hidden | hidden | hidden |\n\n**Rule of thumb**: Use `public` inheritance for "is-a" relationships.\n\n## Types of Inheritance\n\n### Single Inheritance\nOne base, one derived.\n\n### Multiple Inheritance\n\n```cpp\nclass A { public: void fa() {} };\nclass B { public: void fb() {} };\nclass C : public A, public B { };\n\nC c;\nc.fa();  // From A\nc.fb();  // From B\n```\n\n**Diamond Problem**:\n```cpp\nclass A { public: int x; };\nclass B : public A { };\nclass C : public A { };\nclass D : public B, public C { };\n// D d; d.x;  // Ambiguous! Two copies of A\n\n// Solution: virtual inheritance\nclass B : virtual public A { };\nclass C : virtual public A { };\n// Now D has only one copy of A\n```\n\n## The `protected` Keyword\n\nMembers accessible in the class and its derived classes, but not from outside:\n```cpp\nclass Base {\nprotected:\n    int secret;\n};\n\nclass Derived : public Base {\npublic:\n    void setSecret(int s) { secret = s; }  // OK\n};\n```\n\n## Constructor/Destructor Order\n\n- Construction: Base → Derived\n- Destruction: Derived → Base (reverse order)\n\n```cpp\nclass Base {\npublic:\n    Base() { cout << "Base ctor\\\\n"; }\n    ~Base() { cout << "Base dtor\\\\n"; }\n};\n\nclass Derived : public Base {\npublic:\n    Derived() { cout << "Derived ctor\\\\n"; }\n    ~Derived() { cout << "Derived dtor\\\\n"; }\n};\n// Output:\n// Base ctor\n// Derived ctor\n// Derived dtor\n// Base dtor\n```\n\n## Calling Base Constructor\n\n```cpp\nclass Derived : public Base {\npublic:\n    Derived(int a, int b) : Base(a) {  // Call base constructor\n        // ...\n    }\n};\n```\n\n## Best Practices\n1. Use public inheritance only for true "is-a" relationships\n2. Prefer composition ("has-a") over inheritance when possible\n3. Mark destructors virtual in base classes\n4. Avoid deep inheritance hierarchies (max 3-4 levels)',
    code_example: '#include <iostream>\n#include <string>\nusing namespace std;\n\nclass Employee {\nprotected:\n    string name;\n    double salary;\npublic:\n    Employee(string n, double s) : name(n), salary(s) {}\n    virtual double pay() const { return salary; }\n    virtual void work() const { cout << name << " works" << endl; }\n};\n\nclass Manager : public Employee {\n    double bonus;\npublic:\n    Manager(string n, double s, double b) : Employee(n, s), bonus(b) {}\n    double pay() const override { return salary + bonus; }\n    void work() const override { cout << name << " manages" << endl; }\n};\n\nint main() {\n    Employee* e1 = new Employee("Alice", 50000);\n    Employee* e2 = new Manager("Bob", 80000, 20000);\n    cout << e1->pay() << endl;\n    cout << e2->pay() << endl;\n    e2->work();\n    delete e1; delete e2;\n    return 0;\n}'
  },
  {
    id: 'lesson-28',
    title: 'Polymorphism & Virtual Functions',
    category: 'oop',
    order_index: 28,
    content: '## What is Polymorphism?\n\nPolymorphism ("many forms") allows the same interface to behave differently based on the actual object type at runtime. This is achieved through virtual functions.\n\n## Static vs Dynamic Polymorphism\n\n| Type | Mechanism | When Resolved |\n|------|-----------|---------------|\n| Static | Function overloading / templates | Compile-time |\n| Dynamic | Virtual functions | Runtime |\n\n## Virtual Functions\n\nA `virtual` function can be overridden in derived classes. The correct function is called based on the ACTUAL object type, not the pointer type:\n\n```cpp\nclass Shape {\npublic:\n    virtual double area() const { return 0; }\n};\n\nclass Circle : public Shape {\n    double r;\npublic:\n    Circle(double r) : r(r) {}\n    double area() const override { return 3.14159 * r * r; }\n};\n\nclass Rect : public Shape {\n    double w, h;\npublic:\n    Rect(double w, double h) : w(w), h(h) {}\n    double area() const override { return w * h; }\n};\n\nShape* s1 = new Circle(5);\nShape* s2 = new Rect(3, 4);\ncout << s1->area();  // 78.54 (Circle version)\ncout << s2->area();  // 12 (Rect version)\n```\n\n## The `override` Keyword (C++11)\n\nExplicitly marks a function as overriding. The compiler checks that the base function is virtual:\n```cpp\nvoid draw() override;  // Error if base doesn\'t have virtual draw()\n```\n\n## The `final` Keyword (C++11)\n\nPrevents further overriding:\n```cpp\nclass Base {\n    virtual void f() final;  // Cannot override\n};\n\nclass Derived final : public Base { };  // Cannot inherit\n```\n\n## How Virtual Functions Work: The VTable\n\nEach class with virtual functions has a virtual table (vtable) — an array of function pointers. Each object has a hidden `vptr` pointing to its class\'s vtable.\n\n```\nObject s1 (Circle):   vptr → [Circle::area()]\nObject s2 (Rect):     vptr → [Rect::area()]\n```\n\nCalling `s1->area()`:\n1. Follow vptr to vtable\n2. Call function at index 0 (area)\n\n**Overhead**: One vptr per object + one vtable per class. Function call is slightly slower (indirection).\n\n## Virtual Destructors\n\nIf you delete a derived object through a base pointer without a virtual destructor, the derived destructor won\'t be called! This is undefined behavior.\n\n```cpp\nclass Base {\npublic:\n    virtual ~Base() {}\n};\n```\n\n## Pure Virtual Functions & Abstract Classes\n\nA pure virtual function has no implementation in the base class:\n```cpp\nvirtual void draw() = 0;\n```\n\nClasses with at least one pure virtual function are ABSTRACT — cannot be instantiated.\n\n## Best Practices\n1. Always use `override` when overriding\n2. Always make destructors virtual in base classes\n3. Prefer abstract classes for interfaces\n4. Avoid calling virtual functions in constructors/destructors (they don\'t dispatch)',
    code_example: '#include <iostream>\n#include <vector>\nusing namespace std;\n\nclass Media {\npublic:\n    virtual void play() const = 0;\n    virtual ~Media() {}\n};\n\nclass Song : public Media {\n    string title;\npublic:\n    Song(string t) : title(t) {}\n    void play() const override {\n        cout << "Playing song: " << title << endl;\n    }\n};\n\nclass Video : public Media {\n    string name;\npublic:\n    Video(string n) : name(n) {}\n    void play() const override {\n        cout << "Playing video: " << name << endl;\n    }\n};\n\nint main() {\n    vector<Media*> media = {new Song("Bohemian Rhapsody"), new Video("Tutorial")};\n    for (auto m : media) m->play();\n    for (auto m : media) delete m;\n    return 0;\n}'
  },
  {
    id: 'lesson-29',
    title: 'Abstract Classes & Interfaces',
    category: 'oop',
    order_index: 29,
    content: '## Abstract Classes\n\nA class containing at least one pure virtual function is abstract. You cannot create objects of an abstract class.\n\n## Pure Virtual Functions\n\nA pure virtual function has NO implementation in the base class. Derived classes MUST override it (unless they are also abstract):\n\n```cpp\nclass Shape {\npublic:\n    virtual double area() const = 0;    // Pure virtual\n    virtual void draw() const = 0;      // Pure virtual\n    virtual ~Shape() {}\n\n    // Can still have regular methods\n    void display() const { draw(); }\n};\n```\n\n## The "Interface" Pattern\n\nC++ doesn\'t have a dedicated `interface` keyword (unlike Java/C#). Instead, an interface is a class with ALL pure virtual functions:\n\n```cpp\nclass IPrintable {  // Interface (convention: I prefix)\npublic:\n    virtual void print() const = 0;\n    virtual ~IPrintable() {}\n};\n\nclass ISerializable {  // Another interface\npublic:\n    virtual string serialize() const = 0;\n    virtual ~ISerializable() {}\n};\n\nclass Document : public IPrintable, public ISerializable {\npublic:\n    void print() const override { /* ... */ }\n    string serialize() const override { return "{...}"; }\n};\n```\n\n## Why Use Abstract Classes?\n\n1. **Contracts**: Force derived classes to implement certain functions\n2. **Polymorphism**: Write code that works with any derived type\n3. **Design Patterns**: Strategy, Factory, Template Method all rely on abstraction\n\n## Using Abstract Classes as Parameters\n\n```cpp\nvoid processShape(const Shape& s) {\n    cout << "Area: " << s.area() << endl;\n    s.draw();\n}\n\nCircle c(5);\nprocessShape(c);  // Works with any Shape\n```\n\n## Concrete Example\n\n```cpp\nclass Logger {  // Abstract interface\npublic:\n    virtual void log(const string& msg) = 0;\n    virtual ~Logger() {}\n};\n\nclass FileLogger : public Logger {\n    ofstream file;\npublic:\n    void log(const string& msg) override { file << msg << endl; }\n};\n\nclass ConsoleLogger : public Logger {\npublic:\n    void log(const string& msg) override { cout << msg << endl; }\n};\n\n// Client code doesn\'t care about the concrete type!\nvoid process(Logger& logger) {\n    logger.log("Processing started");\n}\n```\n\n## Best Practices\n1. Use abstract classes for interfaces (all pure virtual)\n2. Use abstract classes with some implementation for base classes sharing code\n3. Always provide virtual destructors\n4. Prefer interface-based design for loose coupling\n5. Favor composition over inheritance in implementation',
    code_example: '#include <iostream>\n#include <vector>\n#include <string>\nusing namespace std;\n\nclass IShape {\npublic:\n    virtual double area() const = 0;\n    virtual string name() const = 0;\n    virtual ~IShape() {}\n};\n\nclass Circle final : public IShape {\n    double r;\npublic:\n    Circle(double r) : r(r) {}\n    double area() const override { return 3.14159 * r * r; }\n    string name() const override { return "Circle"; }\n};\n\nclass Square final : public IShape {\n    double side;\npublic:\n    Square(double s) : side(s) {}\n    double area() const override { return side * side; }\n    string name() const override { return "Square"; }\n};\n\nvoid printShape(const IShape& s) {\n    cout << s.name() << " area: " << s.area() << endl;\n}\n\nint main() {\n    Circle c(5);\n    Square sq(4);\n    printShape(c);\n    printShape(sq);\n    return 0;\n}'
  },
  {
    id: 'lesson-30',
    title: 'Operator Overloading & Friend Functions',
    category: 'oop',
    order_index: 30,
    content: '## Operator Overloading\n\nOperators like `+`, `-`, `<<`, `[]` can be overloaded to work with user-defined types. This makes custom types behave like built-in types.\n\n## Overloadable Operators\n\nMost operators can be overloaded: `+ - * / % ^ & | ~ ! = < > += -= *= /= %= ^= &= |= << >> >>= <<= == != <= >= && || ++ -- ->* -> () [] , new new[] delete delete[]`\n\nCannot overload: `::`, `.?`, `.*`, `sizeof`, `typeid`, `?:`\n\n## Syntax\n\n```cpp\nreturn_type operator@(parameters);\n\n// Example: operator+\nFraction operator+(const Fraction& other) const;\n```\n\n## As Member vs Non-Member\n\n### Member Function\n```cpp\nclass Complex {\n    double real, imag;\npublic:\n    Complex operator+(const Complex& other) const {\n        return Complex(real + other.real, imag + other.imag);\n    }\n};\n```\n\n### Non-Member Function (often `friend`)\n```cpp\nclass Complex {\n    friend Complex operator+(const Complex& a, const Complex& b);\n};\n\nComplex operator+(const Complex& a, const Complex& b) {\n    return Complex(a.real + b.real, a.imag + b.imag);\n}\n```\n\nUse non-member when the left operand shouldn\'t be modified (or isn\'t an instance of the class).\n\n## Common Overloads\n\n### `<<` and `>>` (Stream I/O)\n```cpp\nfriend ostream& operator<<(ostream& os, const Point& p) {\n    os << "(" << p.x << ", " << p.y << ")";\n    return os;\n}\n\nfriend istream& operator>>(istream& is, Point& p) {\n    is >> p.x >> p.y;\n    return is;\n}\n```\n\n### `[]` (Subscript)\n```cpp\nint& operator[](int index) { return data[index]; }\nconst int& operator[](int index) const { return data[index]; }\n```\n\n### `()` (Function Call)\n```cpp\nclass Adder {\n    int n;\npublic:\n    Adder(int n) : n(n) {}\n    int operator()(int x) const { return x + n; }\n};\nAdder add5(5);\ncout << add5(10);  // 15\n```\n\n### `++` and `--` (Increment/Decrement)\n```cpp\nNumber& operator++();    // Prefix: ++n\nNumber operator++(int);  // Postfix: n++\n```\n\n## The `friend` Keyword\n\nA `friend` function or class can access private and protected members:\n```cpp\nclass A {\n    int secret;\n    friend void reveal(const A& a);  // Function friend\n    friend class B;                    // Class friend\n};\n```\n\n## Best Practices\n1. Keep operator semantics intuitive (don\'t make `+` do subtraction)\n2. Prefer non-member for symmetric operators (`+`, `-`, `==`)\n3. Always provide both const and non-const `[]`\n4. Make `<<` and `>>` friend functions\n5. Use `friend` sparingly — it breaks encapsulation',
    code_example: '#include <iostream>\nusing namespace std;\n\nclass Fraction {\n    int num, den;\npublic:\n    Fraction(int n, int d) : num(n), den(d) { simplify(); }\n\n    void simplify() {\n        int g = gcd(num, den);\n        num /= g; den /= g;\n    }\n\n    static int gcd(int a, int b) { return b == 0 ? a : gcd(b, a % b); }\n\n    Fraction operator+(const Fraction& o) const {\n        return Fraction(num * o.den + o.num * den, den * o.den);\n    }\n\n    bool operator==(const Fraction& o) const {\n        return num == o.num && den == o.den;\n    }\n\n    friend ostream& operator<<(ostream& os, const Fraction& f) {\n        os << f.num << "/" << f.den;\n        return os;\n    }\n};\n\nint main() {\n    Fraction a(1, 3), b(1, 6);\n    cout << a << " + " << b << " = " << (a + b) << endl;\n    cout << a << " == " << b << " : " << (a == b) << endl;\n    return 0;\n}'
  }
];
export default oopLessons;
