const stlLessons = [
  {
    id: 'lesson-31',
    title: 'STL Iterators',
    category: 'stl',
    order_index: 31,
    content: '## What are Iterators?\n\nIterators are objects that point to elements in a container. They provide a uniform way to traverse different containers without knowing their internal structure. Think of them as generalized pointers.\n\n## Iterator Categories\n\n| Category | Properties | Example Container |\n|----------|-----------|------------------|\n| Input | Read-only, forward | istream_iterator |\n| Output | Write-only, forward | ostream_iterator |\n| Forward | Read/write, forward | forward_list |\n| Bidirectional | Read/write, both directions | list, set, map |\n| Random Access | Read/write, direct access | vector, deque, array |\n\n## Basic Iterator Usage\n\n```cpp\nvector<int> v = {10, 20, 30, 40, 50};\n\nvector<int>::iterator it = v.begin();\nwhile (it != v.end()) {\n    cout << *it << " ";  // Dereference: 10 20 30 40 50\n    ++it;                 // Move to next\n}\n```\n\n## begin() and end()\n\nEvery container provides:\n- `begin()` — iterator to first element\n- `end()` — iterator PAST the last element (not dereferenceable!)\n\n```cpp\nfor (auto it = v.begin(); it != v.end(); ++it) {\n    *it *= 2;  // Modify via iterator\n}\n```\n\n## Const Iterators\n\nRead-only traversal:\n```cpp\nvector<int>::const_iterator cit = v.cbegin();\n// *cit = 42;  // Error! Can\'t modify\n```\n\n## Reverse Iterators\n\nTraverse backwards:\n```cpp\nfor (auto it = v.rbegin(); it != v.rend(); ++it) {\n    cout << *it << " ";  // 50 40 30 20 10\n}\n```\n\n## Iterator Invalidation\n\nOperations that modify container size can invalidate iterators:\n```cpp\nvector<int> v = {1, 2, 3};\nauto it = v.begin();\nv.push_back(4);  // May invalidate all iterators!\n// it is now potentially invalid!\n```\n\n## Iterator Adaptors\n\n```cpp\n#include <iterator>\n\n// Insert iterators\nback_insert_iterator< vector<int> > it(v);\n*it = 10;  // v.push_back(10)\n\nfront_insert_iterator< list<int> > it2(l);\n*it2 = 5;  // l.push_front(5)\n\ninsert_iterator< set<int> > it3(s, s.begin());\n*it3 = 42;  // s.insert(42)\n```\n\n## Range-Based For Loop Internals\n\nThe range-based for loop is syntactic sugar over iterators:\n```cpp\nfor (int x : v) { }  // Compiles to iterator-based loop\n```\n\n## Best Practices\n1. Use `auto` for iterator types\n2. Prefer range-based for when possible\n3. Be aware of iterator invalidation rules\n4. Use `cbegin()`/`cend()` for read-only traversal',
    code_example: '#include <iostream>\n#include <vector>\n#include <set>\n#include <algorithm>\nusing namespace std;\n\nint main() {\n    vector<int> v = {5, 2, 8, 1, 9};\n\n    cout << "Forward: ";\n    for (auto it = v.begin(); it != v.end(); ++it) cout << *it << " ";\n    cout << endl;\n\n    cout << "Reverse: ";\n    for (auto it = v.rbegin(); it != v.rend(); ++it) cout << *it << " ";\n    cout << endl;\n\n    sort(v.begin(), v.end());\n    cout << "Sorted via iterators: ";\n    for (int x : v) cout << x << " ";\n    cout << endl;\n\n    set<int> s = {3, 1, 4, 1, 5, 9};\n    auto found = s.find(4);\n    if (found != s.end()) cout << "Found: " << *found << endl;\n\n    return 0;\n}'
  },
  {
    id: 'lesson-32',
    title: 'Sequence Containers',
    category: 'stl',
    order_index: 32,
    content: '## Sequence Containers Overview\n\nSequence containers maintain the order of elements as they are inserted. Each has different performance trade-offs.\n\n## 1. std::array (C++11)\n\nFixed-size array with STL interface. No overhead over raw arrays.\n\n```cpp\n#include <array>\narray<int, 5> arr = {1, 2, 3, 4, 5};\narr[2];          // No bounds check\narr.at(2);       // Throws out_of_range\narr.front();     // 1\narr.back();      // 5\narr.size();      // 5\n```\n\n## 2. std::vector\n\nDynamic array. Most commonly used container. O(1) amortized push_back, O(n) insert/erase.\n\n```cpp\nvector<int> v;\nv.reserve(1000);         // Pre-allocate\nv.push_back(10);         // Add to end\nv.pop_back();            // Remove from end\nv.insert(v.begin(), 5);  // Insert at front (O(n))\nv.erase(v.begin() + 3); // Erase at position (O(n))\n```\n\n## 3. std::deque (Double-Ended Queue)\n\nLike vector but O(1) push/pop at BOTH ends. Elements NOT contiguous in memory.\n\n```cpp\ndeque<int> dq;\ndq.push_back(10);\ndq.push_front(20);   // O(1) — faster than vector!\ndq.pop_front();       // O(1)\n```\n\n## 4. std::list (Doubly Linked List)\n\nO(1) insert/erase anywhere (if you have the iterator). No random access. High per-element overhead.\n\n```cpp\nlist<int> lst = {1, 2, 3, 4, 5};\nlst.push_front(0);\nlst.push_back(6);\nlst.insert(++lst.begin(), 99);  // Insert after first\nlst.remove(3);                   // Remove all 3s\nlst.sort();                      // Merge sort (stable)\nlst.unique();                    // Remove consecutive duplicates\n```\n\n## 5. std::forward_list (C++11)\n\nSingly linked list. Minimal overhead. Only forward iteration.\n\n```cpp\nforward_list<int> fl = {1, 2, 3};\nfl.push_front(0);      // Only push_front, no push_back\nfl.insert_after(fl.before_begin(), 42);  // Insert at front\n```\n\n## Choosing the Right Container\n\n| Operation | vector | deque | list | forward_list |\n|-----------|--------|-------|------|-------------|\n| Random access | O(1) | O(1) | O(n) | O(n) |\n| Insert/erase at ends | O(1)* | O(1) | O(1) | O(1) |\n| Insert/erase in middle | O(n) | O(n) | O(1)** | O(1)** |\n| Memory overhead | Low | Medium | High | Low |\n\n*Amortized **With iterator\n\n## Best Practices\n1. Default to `vector` — it\'s the most efficient for most use cases\n2. Use `deque` when you need O(1) push_front\n3. Use `list` when you need frequent middle insertions\n4. Use `array` for fixed-size compile-time containers',
    code_example: '#include <iostream>\n#include <vector>\n#include <deque>\n#include <list>\nusing namespace std;\n\nint main() {\n    vector<int> v = {1, 2, 3};\n    v.push_back(4);\n    v.push_back(5);\n    cout << "Vector: "; for (int x : v) cout << x << " "; cout << endl;\n\n    deque<int> dq = {10, 20, 30};\n    dq.push_front(0);\n    dq.push_back(40);\n    cout << "Deque: "; for (int x : dq) cout << x << " "; cout << endl;\n\n    list<int> lst = {5, 2, 8, 1, 9};\n    lst.sort();\n    lst.unique();\n    cout << "List sorted: "; for (int x : lst) cout << x << " "; cout << endl;\n\n    return 0;\n}'
  },
  {
    id: 'lesson-33',
    title: 'Associative Containers (set & map)',
    category: 'stl',
    order_index: 33,
    content: '## What are Associative Containers?\n\nAssociative containers store elements sorted by key, providing O(log n) lookup, insertion, and deletion. They are implemented as balanced binary search trees (typically red-black trees).\n\n## 1. std::set\n\nA sorted collection of unique elements:\n\n```cpp\n#include <set>\nset<int> s = {3, 1, 4, 1, 5, 9};  // Duplicates removed!\n// s = {1, 3, 4, 5, 9}\n\ns.insert(2);    // {1, 2, 3, 4, 5, 9}\ns.erase(4);     // {1, 2, 3, 5, 9}\n\nif (s.find(3) != s.end()) { }  // O(log n) find\nif (s.count(5)) { }            // 1 if present, 0 if not\n\n// Traversal is in sorted order!\nfor (int x : s) cout << x << \" \";  // 1 2 3 5 9\n```\n\n## 2. std::multiset\n\nLike set but allows duplicates:\n```cpp\nmultiset<int> ms = {1, 3, 1, 3, 5};\n// ms = {1, 1, 3, 3, 5}\nms.count(1);  // 2\nms.erase(1);  // Erases ALL 1s!\n```\n\n## 3. std::map\n\nA sorted collection of key-value pairs:\n\n```cpp\n#include <map>\nmap<string, int> ages;\nages[\"Alice\"] = 30;\nages[\"Bob\"] = 25;\nages[\"Charlie\"] = 35;\n\ncout << ages[\"Alice\"];  // 30\n\n// Insertion with structured binding (C++17)\nfor (const auto& [name, age] : ages) {\n    cout << name << \": \" << age << endl;\n}\n```\n\n### Important: [] inserts if missing!\n```cpp\nmap<string, int> m;\ncout << m[\"key\"];   // Returns 0 AND inserts \"key\" with value 0!\n\n// Use this to check existence without inserting:\nif (m.find(\"key\") != m.end()) { }\nif (m.count(\"key\")) { }\n```\n\n## 4. std::multimap\n\nLike map but allows duplicate keys. No [] operator.\n\n```cpp\nmultimap<string, int> mm;\nmm.insert({\"key\", 1});\nmm.insert({\"key\", 2});\nauto range = mm.equal_range(\"key\");\nfor (auto it = range.first; it != range.second; ++it) { }\n```\n\n## Custom Ordering\n\n```cpp\nset<int, greater<int>> desc = {3, 1, 4, 1, 5};  // Descending\n\nstruct CaseInsensitive {\n    bool operator()(const string& a, const string& b) const {\n        return lexicographical_compare(a.begin(), a.end(),\n                                       b.begin(), b.end(),\n                                       [](char c1, char c2) {\n                                           return tolower(c1) < tolower(c2);\n                                       });\n    }\n};\nset<string, CaseInsensitive> words;\n```\n\n## Performance\n\n| Operation | set/map | unordered_set/unordered_map |\n|-----------|---------|---------------------------|\n| Insert | O(log n) | O(1) avg |\n| Find | O(log n) | O(1) avg |\n| Delete | O(log n) | O(1) avg |\n| Traversal | Sorted order | Unsorted |\n\n## Best Practices\n1. Use `set` for sorted unique elements\n2. Use `map` for key-value lookups with ordering\n3. Be careful with `[]` on map — it creates entries!\n4. Use `find()` for existence checks, not `[]`\n5. Consider unordered_* for hash-based (unsorted) lookup',
    code_example: '#include <iostream>\n#include <map>\n#include <set>\n#include <string>\nusing namespace std;\n\nint main() {\n    map<string, int> wordCount;\n    string words[] = {\"the\", \"quick\", \"brown\", \"fox\", \"the\", \"lazy\", \"dog\", \"the\"};\n\n    for (const string& w : words) {\n        wordCount[w]++;\n    }\n\n    cout << \"Word frequencies:\" << endl;\n    for (const auto& [word, count] : wordCount) {\n        cout << \"  \" << word << \": \" << count << endl;\n    }\n\n    set<int> nums = {5, 2, 8, 2, 1, 5, 3};\n    cout << \"Unique sorted: \";\n    for (int n : nums) cout << n << \" \";\n    cout << endl;\n\n    return 0;\n}'
  },
  {
    id: 'lesson-34',
    title: 'Unordered Containers',
    category: 'stl',
    order_index: 34,
    content: '## Hash-Based Containers\n\nUnordered containers use hash tables instead of binary trees. They provide O(1) average-case lookup, insertion, and deletion — much faster than ordered containers.\n\n## std::unordered_set\n\n```cpp\n#include <unordered_set>\nunordered_set<int> s = {3, 1, 4, 1, 5, 9};\ns.insert(2);\ns.erase(4);\n\nif (s.find(3) != s.end()) { }  // O(1) average\n```\n\n## std::unordered_map\n\n```cpp\n#include <unordered_map>\nunordered_map<string, int> scores;\nscores[\"Alice\"] = 95;\nscores[\"Bob\"] = 87;\n\nfor (const auto& [name, score] : scores) {\n    cout << name << \": \" << score << endl;\n}\n```\n\n## How Hash Tables Work\n\n1. **Hash function**: Converts key to an integer (hash code)\n2. **Bucket**: Index = hash_code % num_buckets\n3. **Collision**: Multiple keys with same bucket → chaining (linked list)\n\n```cpp\nstruct Person {\n    string name;\n    int age;\n};\n\n// Custom hash\nstruct PersonHash {\n    size_t operator()(const Person& p) const {\n        return hash<string>()(p.name) ^ (hash<int>()(p.age) << 1);\n    }\n};\n\n// Custom equality\nstruct PersonEq {\n    bool operator()(const Person& a, const Person& b) const {\n        return a.name == b.name && a.age == b.age;\n    }\n};\n\nunordered_set<Person, PersonHash, PersonEq> people;\n```\n\n## Bucket Interface\n\n```cpp\nunordered_set<int> s;\ns.max_load_factor(0.75f);  // Default\ns.rehash(100);              // Reserve buckets\n\ncout << \"Buckets: \" << s.bucket_count() << endl;\ncout << \"Load: \" << s.load_factor() << endl;\n```\n\n## When load_factor exceeds max_load_factor, the table rehashes (all elements are moved to new buckets).\n\n## Unordered vs Ordered\n\n| Aspect | unordered_* (hash) | ordered (tree) |\n|--------|-----------------|---------------|\n| Lookup | O(1) avg | O(log n) |\n| Insert | O(1) avg | O(log n) |\n| Order | Random | Sorted |\n| Memory | Higher | Lower |\n| Requires | Hash function | Comparison |\n\n## When to Use Which\n\n- Use `unordered_*` when: You need fast lookup and don\'t care about order\n- Use `set`/`map` when: You need sorted traversal or range queries\n\n## Best Practices\n1. Default to `unordered_*` for performance-sensitive code\n2. Provide custom hash for user-defined types\n3. Avoid during iteration with modifications (rehashing invalidates iterators)\n4. Pre-allocate with `reserve()` when size is known',
    code_example: '#include <iostream>\n#include <unordered_map>\n#include <string>\nusing namespace std;\n\nint main() {\n    unordered_map<string, int> cache;\n\n    // Simulate expensive computation with caching\n    auto getData = [&](const string& key) {\n        if (cache.count(key)) {\n            cout << \"Cache HIT for \" << key << endl;\n            return cache[key];\n        }\n        cout << \"Cache MISS for \" << key << endl;\n        int value = key.length() * 42;\n        cache[key] = value;\n        return value;\n    };\n\n    cout << getData(\"hello\") << endl;\n    cout << getData(\"world\") << endl;\n    cout << getData(\"hello\") << endl;  // Cache hit\n\n    cout << \"\\nCache size: \" << cache.size() << endl;\n    cout << \"Load factor: \" << cache.load_factor() << endl;\n\n    return 0;\n}'
  },
  {
    id: 'lesson-35',
    title: 'STL Algorithms Overview',
    category: 'stl',
    order_index: 35,
    content: '## The Power of STL Algorithms\n\nThe `<algorithm>` header provides ~100 generic algorithms that work with any container through iterators. Learning them eliminates countless bugs and makes code more expressive.\n\n## Non-Modifying Algorithms\n\n```cpp\n#include <algorithm>\n#include <numeric>\n\nvector<int> v = {3, 1, 4, 1, 5, 9, 2, 6};\n\nauto it = find(v.begin(), v.end(), 4);      // Find first 4\nint cnt = count(v.begin(), v.end(), 1);      // Count occurrences\nbool any = any_of(v.begin(), v.end(), [](int x){ return x > 5; });\nbool all = all_of(...);\nint min = *min_element(v.begin(), v.end());\nint max = *max_element(...);\n```\n\n## Modifying Algorithms\n\n```cpp\nfill(v.begin(), v.end(), 0);              // Set all to 0\nreplace(v.begin(), v.end(), 0, 99);       // Replace 0 with 99\ntransform(v.begin(), v.end(), v.begin(), [](int x){ return x * 2; });\nreverse(v.begin(), v.end());\nrotate(v.begin(), v.begin() + 2, v.end());\n\n// Remove (doesn\'t change size!)\nauto newEnd = remove(v.begin(), v.end(), 0);\nv.erase(newEnd, v.end());  // Erase-remove idiom\n```\n\n## Sorting and Searching\n\n```cpp\nsort(v.begin(), v.end());                // O(n log n)\nstable_sort(v.begin(), v.end());          // Stable sort\npartial_sort(v.begin(), v.begin() + 3, v.end());  // Top 3\nnth_element(v.begin(), v.begin() + 4, v.end());  // Partition around 5th\n\nbool sorted = is_sorted(v.begin(), v.end());\n\nauto it = lower_bound(v.begin(), v.end(), 5);  // First >= 5\nauto it = upper_bound(...);                   // First > 5\nbool found = binary_search(v.begin(), v.end(), 5);\n```\n\n## Numeric Algorithms (<numeric>)\n\n```cpp\n#include <numeric>\n\nint sum = accumulate(v.begin(), v.end(), 0);           // Sum\nint prod = accumulate(v.begin(), v.end(), 1, multiplies<int>());\nint dot = inner_product(a.begin(), a.end(), b.begin(), 0);\nvector<int> prefix;\npartial_sum(v.begin(), v.end(), back_inserter(prefix));\n```\n\n## Set Operations (on sorted ranges)\n\n```cpp\nvector<int> result;\nset_union(a.begin(), a.end(), b.begin(), b.end(), back_inserter(result));\nset_intersection(...);\nset_difference(...);\n```\n\n## Heap Operations\n\n```cpp\nmake_heap(v.begin(), v.end());  // Max heap\npop_heap(v.begin(), v.end());   // Move max to end\nv.pop_back();\nv.push_back(10);\npush_heap(v.begin(), v.end());\nsort_heap(v.begin(), v.end());\n```\n\n## Best Practices\n1. Use STL algorithms instead of raw loops when possible\n2. Combine with lambda expressions for clean code\n3. Know the complexity guarantees\n4. Use the erase-remove idiom for removal',
    code_example: '#include <iostream>\n#include <vector>\n#include <algorithm>\n#include <numeric>\nusing namespace std;\n\nint main() {\n    vector<int> v = {5, 2, 8, 1, 9, 3, 7, 4, 6};\n\n    sort(v.begin(), v.end());\n    cout << "Sorted: "; for (int x : v) cout << x << \" \"; cout << endl;\n\n    auto it = lower_bound(v.begin(), v.end(), 5);\n    cout << "First >= 5 at index: \" << (it - v.begin()) << endl;\n\n    transform(v.begin(), v.end(), v.begin(), [](int x){ return x * x; });\n    cout << "Squared: "; for (int x : v) cout << x << \" \"; cout << endl;\n\n    int sum = accumulate(v.begin(), v.end(), 0);\n    cout << "Sum: \" << sum << endl;\n\n    // Erase-remove: filter out > 50\n    v.erase(remove_if(v.begin(), v.end(), [](int x){ return x > 50; }), v.end());\n    cout << "Filtered: "; for (int x : v) cout << x << \" \"; cout << endl;\n\n    return 0;\n}'
  },
  {
    id: 'lesson-36',
    title: 'Custom Comparators & Function Objects',
    category: 'stl',
    order_index: 36,
    content: '## Why Custom Comparators?\n\nContainers and algorithms often need to compare elements. Custom comparators let you control ordering and equality.\n\n## Comparator Basics\n\nA comparator is a callable that takes two arguments and returns `bool` indicating if the first should come before the second. It must follow **strict weak ordering**:\n- Irreflexive: `comp(a, a)` = false\n- Asymmetric: if `comp(a, b)` then not `comp(b, a)`\n- Transitive: if `comp(a, b)` and `comp(b, c)` then `comp(a, c)`\n\n## Function Pointers as Comparators\n\n```cpp\nbool ascending(int a, int b) { return a < b; }\nbool descending(int a, int b) { return a > b; }\n\nsort(v.begin(), v.end(), ascending);\nsort(v.begin(), v.end(), descending);\nset<int, bool(*)(int,int)> customSet(descending);\n```\n\n## Lambda Comparators (Modern C++)\n\n```cpp\nsort(v.begin(), v.end(), [](int a, int b) { return a > b; });\n\n// Stable sort by even/odd, then by value\nstable_sort(v.begin(), v.end(), [](int a, int b) {\n    if ((a % 2) != (b % 2)) return (a % 2) < (b % 2);\n    return a < b;\n});\n```\n\n## Function Objects (Functors)\n\nClasses with `operator()` that can maintain state:\n\n```cpp\nstruct FrequencyCompare {\n    const unordered_map<string, int>& freq;\n    FrequencyCompare(const auto& f) : freq(f) {}\n\n    bool operator()(const string& a, const string& b) const {\n        if (freq.at(a) != freq.at(b))\n            return freq.at(a) > freq.at(b);  // Higher frequency first\n        return a < b;  // Alphabetically for same frequency\n    }\n};\n\nunordered_map<string, int> freq = {{\"the\", 10}, {\"a\", 5}, {\"an\", 8}};\nvector<string> words = {\"the\", \"a\", \"an\"};\nsort(words.begin(), words.end(), FrequencyCompare(freq));\n```\n\n## Using with Associative Containers\n\n```cpp\nstruct Point {\n    int x, y;\n};\n\nstruct PointCompare {\n    bool operator()(const Point& a, const Point& b) const {\n        if (a.x != b.x) return a.x < b.x;\n        return a.y < b.y;\n    }\n};\n\nset<Point, PointCompare> points;\npoints.insert({3, 4});\npoints.insert({1, 2});\n```\n\n## Comparator for map with custom key\n\n```cpp\nmap<string, int, greater<string>> reverseMap;\n// Keys sorted descending\n```\n\n## The `<=>` Three-Way Comparison (C++20)\n\n```cpp\nstruct Point {\n    int x, y;\n    auto operator<=>(const Point&) const = default;\n};\n\nset<Point> s;  // Automatically uses <=>\n```\n\n## Best Practices\n1. Always maintain strict weak ordering\n2. Use lambdas for simple comparators\n3. Use functors for comparators with state\n4. Pass by const reference for non-trivial types\n5. Default to `auto` parameters for generic lambdas\n\n## Predefined Functors\n\nC++ provides common functors in `<functional>`:\n- `less<T>`, `greater<T>`, `equal_to<T>`\n- `plus<T>`, `minus<T>`, `multiplies<T>`\n\n```cpp\nsort(v.begin(), v.end(), greater<int>());  // Descending\n```',
    code_example: '#include <iostream>\n#include <vector>\n#include <algorithm>\n#include <string>\nusing namespace std;\n\nstruct Score {\n    string name;\n    int points;\n};\n\nint main() {\n    vector<Score> scores = {\n        {\"Alice\", 95}, {\"Bob\", 87}, {\"Charlie\", 95}, {\"Diana\", 92}\n    };\n\n    // Sort by points descending, then name ascending\n    sort(scores.begin(), scores.end(), [](const Score& a, const Score& b) {\n        if (a.points != b.points) return a.points > b.points;\n        return a.name < b.name;\n    });\n\n    for (const auto& [name, points] : scores) {\n        cout << name << \": \" << points << endl;\n    }\n\n    // Using predefined functor\n    vector<int> nums = {5, 2, 8, 1, 9};\n    sort(nums.begin(), nums.end(), greater<int>());\n    cout << \"Descending: \";\n    for (int n : nums) cout << n << \" \";\n    cout << endl;\n\n    return 0;\n}'
  }
];
export default stlLessons;
